### ISSUE TITLE
Crash when collecting reports

### ISSUE THREAD

**Issue by ericvergnaud** [pytest-dev/pytest-asyncio#1015]
`pytest-cov `crashes when `pytest-asyncio `is installed and used (i.e. some tests are `async).

The crash is as follows:
```
DataError: Can't combine statement coverage data with branch data
For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
  config.hook.pytest_runtestloop(session=session)
```
From the reference, it seems the culprit is `pytest-asyncio `using an old style event loop ?

**Comment by ericvergnaud** [comment]
The issue is caused by using jointly `pytest-cov `and `pytest-asyncio`

**Comment by seifertm** [comment]
Can you provide a small example that reproduces the error?

**Comment by ericvergnaud** [comment]
Mmm... can't reproduce it anymore. Maybe it was caused by a corrupt venv...

**Comment by ericvergnaud** [comment]
I can reproduce it again, and also found the following:
https://github.com/nedbat/coveragepy/issues/512
The code I'm testing creates child processes, so it smells like the issue is not within asyncio, although disabling it prevents execution of the code that triggers it

**Comment by seifertm** [comment]
@ericvergnaud Thanks for the update. Let us know if there's anything to investigate from pytest-asyncio side.
