### ISSUE TITLE
Coroutine Mocks

### ISSUE THREAD

**Issue by cartertinney** [pytest-dev/pytest-asyncio#108]
I've been using pytest-asyncio in combination with pytest-mock and run into an issue with regard to mocking coroutine functions: It seems there is no way to mock a coroutine such that the resulting MagicMock can function as a coroutine, with respect to the await keyword. Attempting to results in the following error:

TypeError: object MagicMock can't be used in 'await' expression

I understand that other libraries, such as asynctest have this functionality, but I'd really like to stay within pytest and not mix testing libraries. Would it be possible to get this feature added? Our product heavily relies upon mocking for tests, and we have just introduced an async library, which presents us a big issue in continuing to use pytest.

**Comment by asfaltboy** [comment]
It appears one can use an `asyncio.Future` or `asyncio.coroutine` to create an awaitable object which can then be assigned to a `Mock.return_value`. I've only used the former myself:

```python
@pytest.mark.asyncio
def test_some_thing():
    future = asyncio.Future()
    future.set_result('whatever result you want')
    with mock.patch('some_thing', return_value=future) as mock:
        await some_thing(1, 2, 3)
    mock.assert_called_with(1, 2, 3)
```

Ref: https://stackoverflow.com/a/46326234/484127

(not sure if there is a more official recommendation somewhere)

**Comment by asvetlov** [comment]
1. async mocking is out of scope of the project.
2. Python 3.8 supports AsyncMock out-of-the-box in `unittest.mock` module. The pull request has had landed a week ago. This is *official* recommendation :)

**Comment by Pajinek** [comment]
>     1. async mocking is out of scope of the project.
> 
>     2. Python 3.8 supports AsyncMock out-of-the-box in `unittest.mock` module. The pull request has had landed a week ago. This is _official_ recommendation :)

I confirmed that this issue is not related with python 3.8+

**Comment by ZhenTek** [comment]
using context manger instead of decorator, with patch.object(ProductionClass, 'method', return_value=None) as mock_method:
https://docs.python.org/3/library/unittest.mock.html#patch-object

**Comment by asvetlov** [comment]
Nothing to do here, please use `unittest.mock.AsyncMock`.
