### ISSUE TITLE
setup_module cannot be a coroutine?

### ISSUE THREAD

**Issue by f0ff886f** [pytest-dev/pytest-asyncio#119]
Hi, I have a TestClass, a bunch of test functions there, and a fixture that returns a handle to an async-based resource. Before the async world, I could use the setup_module function and guarantee to run code once before my tests.

I would like to achieve the same, run a coroutine once before any tests/fixtures are run. However, no amount of marking setup_module as asyncio would get it work...

Is this possible? I don't care about sharing the event_loop to tests, because this is about cleaning up potential state before an invocation of pytest.

**Comment by and-semakin** [comment]
Hi, @f0ff886f. I have the same question: is there any built-in possibility to run `async` setup/teardown methods?

For now I use following hacky solution:

```python
import asyncio

def run_until_complete(function: Callable) -> Callable:
    @functools.wraps(function)
    def wrapper(*args: Any, **kwargs: Any) -> Any:
        return asyncio.get_event_loop().run_until_complete(function(*args, **kwargs))

    return wrapper

class TestSomething:
    @classmethod
    @run_until_complete
    async def setup_class(cls):
        await asyncio.sleep(1)
```

But it doesn't work after update from pytest 3 to 4, I don't know why. `setup_class` doesn't get its required `cls` argument.

**Comment by HuiiBuh** [comment]
Is there an update to this?

**Comment by simonfagerholm** [comment]
@HuiiBuh What happens if you use a pytest fixture instead of `setup_class`?

**Comment by HuiiBuh** [comment]
It is working with the fixtures.  
I just think that fixtures are not that easy to understand and try not to use them to much. `setup_class` would have been perfect.   
I am currently using another workaround, in this case a custom decorator function.

**Comment by asvetlov** [comment]
pytest has no *official* hook for overriding `setup_*()`/`teardown_()`.
Using hacks based on internal API access is dangerous and error-prone.

I think we should not touch it.
