### ISSUE TITLE
Could not find suitable distribution for Requirement.parse('pytest-asyncio')

### ISSUE THREAD

**Issue by wiliamsouza** [pytest-dev/pytest-asyncio#13]
`easy_install` is not capable[1] of install `pytest-asyncio` I know `pip` is the tool for the job but when you use [setup.py](https://github.com/wiliamsouza/echo/blob/master/setup.py#L12-L19) to manage requirements it uses `easy_install` for it. ~~I think the problem could be the name of wheel package that is `pytest_asyncio` with `_`~~.

[1] https://packaging.python.org/en/latest/pip_easy_install.html

```
$ easy_install pytest-asyncio
Searching for pytest-asyncio
Reading https://pypi.python.org/simple/pytest-asyncio/
No local packages or download links found for pytest-asyncio
error: Could not find suitable distribution for Requirement.parse('pytest-asyncio')
(test)wiliam@vostro:~/.../test$ easy_install pytest_asyncio
Searching for pytest-asyncio
Reading https://pypi.python.org/simple/pytest_asyncio/
No local packages or download links found for pytest-asyncio
error: Could not find suitable distribution for Requirement.parse('pytest-asyncio')
```

**Comment by Tinche** [comment]
I think the problem is I only publish wheels, and easy_install can't handle wheels.

Pip really is the future, and easy_install a legacy thing. Could you be persuaded to use pip instead? (An option is to easy_install pip, then use pip...)

**Comment by wiliamsouza** [comment]
@Tinche Yes, that's correct.
The problem is not me is the `setup.py` that keep using `easy_install` for some internal things like install requirements defined inside it. Please see an example here https://github.com/wiliamsouza/echo/blob/master/setup.py#L18. I made a workaround here https://github.com/wiliamsouza/echo/commit/66e28d4aef9e0556e0450ee99eb5f76473425cb6. If you provides a source dist you don't broke `setup.py` and everyone using `pip` will keep using wheels for default.

**Comment by nicoddemus** [comment]
@Tinche any reason for not also providing a `sdist`? That seems to me to be the standard practice, publish both `sdist` and `wheels` whenever possible.

**Comment by Tinche** [comment]
@wiliamsouza Ah, you're using tests_require. Personally, I've switched to using a special requirements.txt for test requirements, mostly because of this situation of setuptools using easy_install for the requirements (you miss all the others benefits of pip too).

@nicoddemus Well, as I understand it wheels are superior to sdists even in the pure Python case (faster installation, no arbitrary code execution during installation). Since this is a Python 3 project I thought we'd just use the modern goodies off the bat. I guess there'd be no harm providings sdists too, other than the 30 seconds more effort any time a release is made...

**Comment by nicoddemus** [comment]
I guess `sdist` is the plain-old dist format which can be used by absolutely anyone, so it makes sense to always provide them. For example, I'm not sure you can create [conda](http://conda.pydata.org/) packages directly from wheels, but certainly you can from `sdist`s.

**Comment by Tinche** [comment]
I've just pushed out 0.2.0 to PyPI, including a sdist, so this should now work.

**Comment by wiliamsouza** [comment]
@Tinche Thanks!

**Comment by smurfix** [comment]
So close this issue already ;-)
