### ISSUE TITLE
`@patch` decorator is not applied to async test function

### ISSUE THREAD

**Issue by smolcoder** [pytest-dev/pytest-asyncio#130]
The following code illustrates the example when patching a module level variable has no effect on async test function, however it works fine if decorator is applied to a non-async function or patching is done as context manager:

```python
FOO = 1

@pytest.mark.asyncio
@patch('test.service.test_service_core.FOO', 2)
async def test_foo():
    assert FOO == 2  # FAILS

@pytest.mark.asyncio
async def test_foo():
    with patch('test.service.test_service_core.FOO', 2):
        assert FOO == 2  # PASSES

@patch('test.service.test_service_core.FOO', 2)
def test_bar():
    assert FOO == 2  # PASSES
```

Is it a bug?

**Comment by KyleKreutzer** [comment]
As stated above, this is a `unittest.mock` limitation. Using https://pypi.org/project/asynctest/ should help you solve this issue.

**Comment by simonfagerholm** [comment]
@smolcoder Would you mind closing this?

**Comment by smolcoder** [comment]
Thanks!

**Comment by ZhenTek** [comment]
using context manger instead of decorator, with patch.object(ProductionClass, 'method', return_value=None) as mock_method:
https://docs.python.org/3/library/unittest.mock.html#patch-object
