### ISSUE TITLE
TypeError: attrs() got an unexpected keyword argument 'eq'

### ISSUE THREAD

**Issue by sumankanukollu** [pytest-dev/pytest-asyncio#137]
Hi,

I am getting the Error "TypeError: attrs() got an unexpected keyword argument 'eq'", when I run the test.
Environment:
##############
  Python 3.6.8

Steps followed:
###########
   1. Cloned the repo
   2. python3 setup.py build
   3. python3 setup.py install
After that trying to run scripts, but stuck at Type Error message.

Can anyone please help.

**Comment by sumankanukollu** [comment]
Its a "hypothesis" package issue.
Working fine after downgrade the package to =3.73.1

**Comment by jeffsilverm** [comment]
This is due to an out of date version of attrs.  I know that version 19.1.0 fails.  I know that version 22.1.0 works properly.  You might find references to Twisted when searching for this problem.   If you do, then you are getting warm but you haven't actually gotten to the problem yet.
