### ISSUE TITLE
pytest.mark.asyncio flagging is mistakes prone - make it automatic

### ISSUE THREAD

**Issue by uriva** [pytest-dev/pytest-asyncio#144]
Run a test regardless of its async nature, without requiring the user to flag the file or individual functions.

**Comment by Tinche** [comment]
Sorry, I considered it and decided against it because it makes testing other async frameworks much harder in the same codebase.

Consider https://github.com/pytest-dev/pytest-asyncio#pytestmarkasyncio for a little boilerplate reduction instead.

**Comment by uriva** [comment]
also I would like to suggest raising an exception in case an async test was not marked - as me and others are making this mistake all the time.

**Comment by Tinche** [comment]
Curio and trio come to mind. As for raising an error on unmarked test cases - might not be a bad idea. But should be done in pytest itself probably.

**Comment by uriva** [comment]
ok will try there, thanks

**Comment by uriva** [comment]
actually another idea that occurred to me - why not have a flag for this behaviour? then we only need to remember it once

**Comment by Tinche** [comment]
PRs welcome, let's discuss it there :)
