### ISSUE TITLE
Hypothesis test fail because of change in Hypothesis

### ISSUE THREAD

**Issue by simonfagerholm** [pytest-dev/pytest-asyncio#145]
See PR #142 where it first occurs, but it will happen on all builds after last of feb because of https://github.com/HypothesisWorks/hypothesis/pull/2356.

@Zac-HD maybe you can help with a fix as you are involved in both this and hypothesis package.

Basically the problem is that the even_loop is function scope.

**Comment by Zac-HD** [comment]
We'll need to do one of two things:

- If the `event_loop` fixture can safely be shared between tests, make it `session` (or `module`) scoped.
- If it *can't* be shared between tests, the current situation is already broken and this warning has just exposed that latent bug!

I suspect that the latter case is correct, and the response is simply "you cannot use Hypothesis with a fixture-provided event loop" (and so `test_can_use_fixture_provided_event_loop` can be deleted).  In this case we may also need to replace the Hypothesis-specific part with `get_event_loop()` to use `asyncio.run()` instead for proper isolation.

**Comment by simonfagerholm** [comment]
In the documentation I spotted this:

> All scopes are supported, but if you use a non-function scope you will need to redefine the event_loop fixture to have the same or broader scope. Async fixtures need the event loop, and so must have the same or narrower scope than the event_loop fixture.

So I think alternative 1 would be possible. I can fix the test in a PR if you agree that that would be best, @Zac-HD.

**Comment by Zac-HD** [comment]
Yep, using a broader scope sounds good then :+1:
