### ISSUE TITLE
v0.11 AttributeError: type object 'Function' has no attribute 'from_parent'

### ISSUE THREAD

**Issue by yuval-lb** [pytest-dev/pytest-asyncio#155]
my configuration is:
platform linux -- Python 3.6.10, pytest-4.0.2, py-1.8.1, pluggy-0.13.1
plugins: asyncio-0.11.0, mock-3.1.0

got me exception:
_______ ERROR collecting <test> ________
/usr/local/lib/python3.6/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
/usr/local/lib/python3.6/site-packages/pluggy/mantestos/allocator/tests/test_reload_machines.pyager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/local/lib/python3.6/site-packages/pluggy/manager.py:87: in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
/usr/local/lib/python3.6/site-packages/_pytest/python.py:196: in pytest_pycollect_makeitem
    res = outcome.get_result()
/usr/local/lib/python3.6/site-packages/pytest_asyncio/plugin.py:39: in pytest_pycollect_makeitem
    item = pytest.Function.from_parent(collector, name=name)
E   AttributeError: type object 'Function' has no attribute 'from_parent'

going back to v0.10 the test pass.

**Comment by simonfagerholm** [comment]
@yuval-lb You are using an incompatible version of pytest. Install the correct version and it will work.

**Comment by Lenka42** [comment]
@simonfagerholm experiencing same issue in following setup:
platform linux -- Python 3.8.0, pytest-5.2.1, py-1.8.0, pluggy-0.13.0
plugins: cov-2.8.1, asyncio-0.11.0

**Comment by simonfagerholm** [comment]
@Lenka42 The same answer applies to you, incompatible pytest version. Install the correct version and you should be fine.
I did some testing and pip seems to handle this automatically, what are you using?

**Comment by yuval-lb** [comment]
@simonfagerholm thanks for the fast replay - I will check that out.

**Comment by Lenka42** [comment]
@simonfagerholm I figured out, that this issue occurs only when I do pip install in travis :facepalm: 
Here is our requirements list: https://github.com/wialon/gmqtt/blob/master/setup.py#L30
And here is log from travis run: 
```
$ pip install -r requirements_test.txt
Processing /home/travis/build/Lenka42/gmqtt
Requirement already satisfied: atomicwrites>=1.3.0 in /home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages (from gmqtt==0.6.4->-r requirements_test.txt (line 2)) (1.3.0)
Requirement already satisfied: attrs>=19.1.0 in /home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages (from gmqtt==0.6.4->-r requirements_test.txt (line 2)) (19.3.0)
Collecting codecov>=2.0.15
  Downloading https://files.pythonhosted.org/packages/4d/86/7135a1db448c3bd478a7bbd817bfe3d80200eec7a89d320d574644879528/codecov-2.0.22-py2.py3-none-any.whl
Collecting coverage>=4.5.3
  Downloading https://files.pythonhosted.org/packages/52/38/53a28fcbe77f56f92d45f9961feca85caebe7424b63a10b07aa8607a4f8d/coverage-5.1-cp38-cp38-manylinux1_x86_64.whl (229kB)
Requirement already satisfied: more-itertools>=7.0.0 in /home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages (from gmqtt==0.6.4->-r requirements_test.txt (line 2)) (7.2.0)
Requirement already satisfied: pluggy>=0.11.0 in /home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages (from gmqtt==0.6.4->-r requirements_test.txt (line 2)) (0.13.0)
Requirement already satisfied: py>=1.8.0 in /home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages (from gmqtt==0.6.4->-r requirements_test.txt (line 2)) (1.8.0)
Collecting pytest-asyncio>=0.10.0
  Downloading https://files.pythonhosted.org/packages/b1/c2/d0cc08b6e3914e269080f5db53a4e9e676d3d37570f91f6d99681df7ee09/pytest_asyncio-0.11.0-py3-none-any.whl
Collecting pytest-cov>=2.7.1
  Downloading https://files.pythonhosted.org/packages/b9/54/3673ee8be482f81527678ac894276223b9814bb7262e4f730469bb7bf70e/pytest_cov-2.8.1-py2.py3-none-any.whl
Requirement already satisfied: pytest>=4.5.0 in /home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages (from gmqtt==0.6.4->-r requirements_test.txt (line 2)) (5.2.1)
Requirement already satisfied: six>=1.12.0 in /home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages (from gmqtt==0.6.4->-r requirements_test.txt (line 2)) (1.12.0)
Collecting uvloop>=0.14.0
  Downloading https://files.pythonhosted.org/packages/bd/c0/38d013d6cbfa58e7aa8b32bf5095196a3d70dbff90a754817ebf3f49dd74/uvloop-0.14.0-cp38-cp38-manylinux2010_x86_64.whl (4.7MB)
Collecting requests>=2.7.9
  Downloading https://files.pythonhosted.org/packages/1a/70/1935c770cb3be6e3a8b78ced23d7e0f3b187f5cbfab4749523ed65d7c9b1/requests-2.23.0-py2.py3-none-any.whl (58kB)
Requirement already satisfied: wcwidth in /home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages (from pytest>=4.5.0->gmqtt==0.6.4->-r requirements_test.txt (line 2)) (0.1.7)
Requirement already satisfied: packaging in /home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages (from pytest>=4.5.0->gmqtt==0.6.4->-r requirements_test.txt (line 2)) (19.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages (from requests>=2.7.9->codecov>=2.0.15->gmqtt==0.6.4->-r requirements_test.txt (line 2)) (2019.9.11)
Collecting chardet<4,>=3.0.2
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting idna<3,>=2.5
  Downloading https://files.pythonhosted.org/packages/89/e3/afebe61c546d18fb1709a61bee788254b40e736cff7271c7de5de2dc4128/idna-2.9-py2.py3-none-any.whl (58kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading https://files.pythonhosted.org/packages/e1/e5/df302e8017440f111c11cc41a6b432838672f5a70aa29227bf58149dc72f/urllib3-1.25.9-py2.py3-none-any.whl (126kB)
Requirement already satisfied: pyparsing>=2.0.2 in /home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages (from packaging->pytest>=4.5.0->gmqtt==0.6.4->-r requirements_test.txt (line 2)) (2.4.2)
Building wheels for collected packages: gmqtt
  Building wheel for gmqtt (setup.py): started
  Building wheel for gmqtt (setup.py): finished with status 'done'
  Created wheel for gmqtt: filename=gmqtt-0.6.4-cp38-none-any.whl size=22373 sha256=e744b702c1236e83568f1b5d8f79320d6122c2e5b4f2efc9591cc696c2c48e14
  Stored in directory: /tmp/pip-ephem-wheel-cache-61ydlln4/wheels/ba/3e/15/30ec30e0752ded1d525d2c31a2d66bd22ed6b749267e637ff2
Successfully built gmqtt
ERROR: pytest-asyncio 0.11.0 has requirement pytest>=5.4.0, but you'll have pytest 5.2.1 which is incompatible.
Installing collected packages: chardet, idna, urllib3, requests, coverage, codecov, pytest-asyncio, pytest-cov, uvloop, gmqtt
Successfully installed chardet-3.0.4 codecov-2.0.22 coverage-5.1 gmqtt-0.6.4 idna-2.9 pytest-asyncio-0.11.0 pytest-cov-2.8.1 requests-2.23.0 urllib3-1.25.9 uvloop-0.14.0
```
And despite there is an error in log, exit code is valid, or it's just travis ignoring the error :disappointed:

**Comment by LeCuay** [comment]
Same here! So in my case Travis is installing pytest 5.3.2 and shows error but ignores it

**Comment by simonfagerholm** [comment]
@yuval-lb Can this be closed? As the problem seems unrelated to pytest-asyncio

**Comment by yuval-lb** [comment]
@simonfagerholm yes, thanks.

**Comment by simonfagerholm** [comment]
@yuval-lb I think you need to do it yourself (unless you ask a admin to do it), the button should be beside the comment button

**Comment by Andrew-Chen-Wang** [comment]
For those who also get this error, the compatible version noted in the changelog says to use pytest>=5.4.0.

**Comment by serhiy-storchaka** [comment]
There is a problem with dependabot when try to update old `pytest` and `pytest-asyncio`. It cannot update `pytest-asyncio` because the old `pytest` does not have Function.from_parent. It cannot update `pytest` because it raises a deprecation warning with the old `pytest-asyncio` which is a blocker for strict settings in CI.

**Comment by simonfagerholm** [comment]
I'm not sure I follow...
old `pytest-asyncio` should work with old `pytest` and new `pytest-asyncio` should work with new `pytest`

**Comment by serhiy-storchaka** [comment]
Yes, but you cannot use old `pytest-asyncio` with new `pytest` (if warnings filter is set to error) and new `pytest-asyncio` with old `pytest`. This causes a conflict for dependabot which updates dependencies one by one. This conflit cannot be solved without human intervention.

Currently I'm resolving conflicts in several projects with zero tolerance to warnings, and it is boring: temporary silence warnings, regenerate PR for updating `pytest`, wait until tests be passed, merge it, regenerate PR for updating `pytest-asyncio`, wait until tests be passed, merge it, restore old settings.
