### ISSUE TITLE
we are getting error while installing pytest error: Could not find suitable distribution for Requirement.parse('pytest')

### ISSUE THREAD

**Issue by bimith** [pytest-dev/pytest-asyncio#165]
At present situation we cannot use the internet on the server am using python 3.5.3
please suggest what is the another way to install the pytest
zip_safe flag not set; analyzing archive contents...
prepare_env_test_mode.__pycache__.clone_build_start_server.cpython-35: module references __file__
prepare_env_test_mode.__pycache__.take_backup.cpython-35: module references __file__
creating 'dist/mysql_autoxtrabackup-1.5.5-py3.5.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing mysql_autoxtrabackup-1.5.5-py3.5.egg
removing '/usr/local/lib/python3.5/site-packages/mysql_autoxtrabackup-1.5.5-py3.5.egg' (and everything under it)
creating /usr/local/lib/python3.5/site-packages/mysql_autoxtrabackup-1.5.5-py3.5.egg
Extracting mysql_autoxtrabackup-1.5.5-py3.5.egg to /usr/local/lib/python3.5/site-packages
mysql-autoxtrabackup 1.5.5 is already the active version in easy-install.pth
Installing autoxtrabackup script to /usr/local/bin

Installed /usr/local/lib/python3.5/site-packages/mysql_autoxtrabackup-1.5.5-py3.5.egg
Processing dependencies for mysql-autoxtrabackup==1.5.5
Searching for pytest
Reading https://pypi.python.org/simple/pytest/
Download error on https://pypi.python.org/simple/pytest/: [Errno -2] Name or service not known -- Some packages may not be found!
Couldn't find index page for 'pytest' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [Errno -2] Name or service not known -- Some packages may not be found!
No local packages or working download links found for pytest
error: Could not find suitable distribution for Requirement.parse('pytest')

**Comment by Tinche** [comment]
Out of scope for this project, I'm afraid :)
