### ISSUE TITLE
Task was destroyed but it is pending!

### ISSUE THREAD

**Issue by Cimmanuel** [pytest-dev/pytest-asyncio#179]
I just recently integrated `graphene_subscriptions` into my project and I followed the example test to write my own. I have:

```python
async def query(query, communicator, variables=None):
    await communicator.send_json_to(
        {"id": 1, "type": "start", "payload": {
            "query": query, "variables": variables}}
    )


@pytest.mark.asyncio
@pytest.mark.django_db
async def test_user_created_subscription():
    post_save.connect(
        post_save_subscription, sender=models.User, dispatch_uid='user_create_post_save'
    )

    communicator = WebsocketCommunicator(
        GraphqlSubscriptionConsumer, "/graphql/")
    connected, subprotocol = await communicator.connect()
    assert connected

    await query(
        '''
        subscription {
            userCreated {
                firstName
                lastName
            }
        }

        ''',
        communicator
    )

    user = await sync_to_async(models.User.objects.create)(
        first_name='Test', last_name='User', sex='male', password='helloworld'
    )
    
    response = await communicator.receive_json_from()

    assert response['payload'] == {
        'data': {'userCreated': {
            'firstName': user.first_name, 'lastName': user.last_name}},
        'errors': None,
    }

    post_save.disconnect(
        post_save_subscription, sender=models.User, dispatch_uid='user_create_post_save'
    )
```
But when I run the test, it passes but I also get the following:
```
Task was destroyed but it is pending!
task: <Task pending coro=<double_to_single_callable.<locals>.new_application() running at /root/.local/share/virtualenvs/app-lp47FrbD/lib/python3.7/site-packages/asgiref/compatibility.py:34> wait_for=<Task pending coro=<Queue.get() running at /usr/local/lib/python3.7/asyncio/queues.py:159> wait_for=<Future cancelled> cb=[<TaskWakeupMethWrapper object at 0x7f4d78297950>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Queue.get() running at /usr/local/lib/python3.7/asyncio/queues.py:159> wait_for=<Future cancelled> cb=[<TaskWakeupMethWrapper object at 0x7f4d78297950>()]>
```
What's wrong and how do I get past this? Thanks!

**Comment by asvetlov** [comment]
Sorry, I cannot find what task is not awaited without a reproducible example.

**Comment by seifertm** [comment]
@Cimmanuel I know our response comes pretty late. If you could already solve your problem, that's great! As Andrew already mentioned, we cannot really help you without a reproducible example.

Feel free to reopen this issue, if you're still having problems.

**Comment by evbo** [comment]
@seifertm can you offer any general suggestions? I'm afraid I too am hitting this issue and without a small reproducible example and it seems there's a fair number of upvotes. 

What can cause this exception? My understanding is `@pytest.mark.asyncio` has a finally clause so is it possibly not closing all tasks?

**Comment by seifertm** [comment]
@evbo The exception is emitted by asyncio Tasks when they're garbage collected while in the state _Pending_. That means the task has neither finished nor has it been cancelled.

If I were you I'd check two things:
1. the code either awaits or cancels the task
2. you code has a (strong) reference to the task. Event loops only maintain weak references to tasks, which may cause tasks to be garbage collected prematurely.

Tasks that log this error do so via the event loop's exception handler, if I recall correctly. You may have some luck debugging your application by implementing a custom exception handler.
