### ISSUE TITLE
Treating the "coroutine was never awaited" RuntimeWarning as an error

### ISSUE THREAD

**Issue by puddly** [pytest-dev/pytest-asyncio#184]
Here's a simple test case:

```Python
# test_raise_warning.py

import pytest
import asyncio


@pytest.mark.asyncio
async def test_raise_warning():
    async def foo():
        pass

    foo()
    await asyncio.sleep(0.5)
```

And how I setup my test environment:

```shell
$ python3.8 -m venv venv
$ source venv/bin/activate
(venv) $ pip install pytest pytest-asyncio
```

If you try running `pytest` normally, it logs a warning:

```console
$ pytest test_raise_warning.py
=========================== test session starts ===========================
platform darwin -- Python 3.8.3, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /private/tmp
plugins: asyncio-0.14.0
collected 1 item

test_raise.py .                                                     [100%]

============================ warnings summary =============================
test_raise_warning.py::test_raise_warning
  /private/tmp/test_raise_warning.py:10: RuntimeWarning: coroutine 'test_raise_warning.<locals>.foo' was never awaited
    foo()

-- Docs: https://docs.pytest.org/en/stable/warnings.html
====================== 1 passed, 1 warning in 0.54s =======================
```

However, passing `-Werror` silences it completely:

```console
$ pytest -Werror test_raise_warning.py
=========================== test session starts ===========================
platform darwin -- Python 3.8.3, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /private/tmp
plugins: asyncio-0.14.0
collected 1 item

test_raise_warning.py .                                             [100%]

============================ 1 passed in 0.52s ============================
```

I'm trying to get this test case to fail. The `with warnings.catch_warnings():  ...` context manager doesn't work either because I think it needs to be around the call to `loop.run_until_complete()` call.

Am I misconfiguring something?

**Comment by graingert** [comment]
I think you need to use pytest.ini's `filterwarnings = "error"` and set `sys.unraisablehook` before and run `gc.collect` after each test

**Comment by puddly** [comment]
@graingert Oh, you actually introduced `sys.unraisablehook` into CPython. Thank you!

I see now that this issue is related to https://github.com/pytest-dev/pytest/issues/5299

I'll try to write a plugin for it or something, I've not worked with pytest internals before so it will take some time.

**Comment by graingert** [comment]
@puddly my need for this feature is now more pressing, have you got something I can collaborate on?

**Comment by puddly** [comment]
I've implemented this as a separate plugin https://github.com/puddly/pytest-unraisable/
