### ISSUE TITLE
RuntimeError: This event loop is already running

### ISSUE THREAD

**Issue by timkofu** [pytest-dev/pytest-asyncio#186]
I got the above exception when decorating a test coroutine with `@pytest.mark.asyncio` that has a 
 `starlette.testclient.TestClient`  instantiation inside it.

**Comment by streeck** [comment]
Maybe coming a bit late on this, but it could possibly help someone else.

I believe the "correct" way is outlined in FastAPI's documentation over [here](https://fastapi.tiangolo.com/advanced/async-tests/), since it's based on Starlette it should give you an idea.

**Comment by graingert** [comment]
I think we fixed this in the latest Starlette v0.15.0

**Comment by timkofu** [comment]
> I think we fixed this in the latest Starlette v0.15.0, as we now use an anyio blocking portal

Confirmed. Working without nest-asyncio now.

**Comment by graingert** [comment]
@timkofu you might also like to try `@pytest.mark.anyio` with the `httpx.AsyncClient`
