### ISSUE TITLE
Option to run test using loop.run_forever

### ISSUE THREAD

**Issue by bphillips-exos** [pytest-dev/pytest-asyncio#187]
I have a use case where a custom loop needs to be run with `run_forever` rather than `run_until_complete`. There doesn't seem to be anyway to control this behavior at the moment, so I've opted to create a separate marker very similar to `pytest.mark.asyncio`. 

My question is, is there anyway to elegantly modify the behavior of pytest-asyncio to use `run_forever` rather than creating a brand new marker?

**Comment by asvetlov** [comment]
asyncio-compliant event loop should support both `run_forever()` and `run_until_complete()`.

Actually, asyncio itself implements `run_until_complete()` on top of `run_forever`, [40 lines of code](https://github.com/python/cpython/blob/main/Lib/asyncio/base_events.py#L601-L637)

I think the custom loop should be modified, not pytest-asyncio.

@Tinche I suggest closing the issue.
