### ISSUE TITLE
Drop support for Python 3.5

### ISSUE THREAD

**Issue by seifertm** [pytest-dev/pytest-asyncio#191]
Python 3.5 [reached end-of-life](https://www.python.org/dev/peps/pep-0478/#release-schedule) on 2020-09-30. We should consider dropping support for it.

I would happily take care of it, either in a separate PR or as part of #190 .

**Comment by Tinche** [comment]
I agree, we can drop 3.5. Could you put together a PR and I can merge that in too. Thanks!

**Comment by seifertm** [comment]
Python 3.5 support was removed as of v0.15
