### ISSUE TITLE
Add type annotations

### ISSUE THREAD

**Issue by jeremad** [pytest-dev/pytest-asyncio#198]

**Comment by asvetlov** [comment]
For what purpose?

**Comment by RobertCraigie** [comment]
@asvetlov For https://github.com/RobertCraigie/prisma-client-py I use strict mode with [pyright](https://github.com/microsoft/pyright) which means that the libraries I use must provide type hints.

This wasn't an issue for me as I only used `pytest-asyncio` though `pytest` until the recent 0.17.0 release as I now need to use `async_mode = strict` which means I need to use the `pytest_asyncio.fixture` decorator. Pyright does not like that the decorator is untyped and reports errors. The simple workaround is to write my own typed decorator that wraps `pytest_asyncio.fixture` however it would be nice if this was already provided.

On top of that, the main benefit for adding type annotations is the improved IDE experience with auto-completion and error checking.

**Comment by asvetlov** [comment]
Regarding `@fixture` -- you are right. The type info will be added soon.

For other parts the benefit is not so obvious.
`pytest` itself is in the middle of adding type information, it has very many *private* types now. I consider re-using these underscored types as a bad practice. Later the situation will be improved, sure. I did the same transition for aiohttp 3.-4 years ago :)
Moreover, types for fixtures are not inferred by `mypy`. It could be done by a mypy plugin theoretically but the plugin doesn't exist yet as far as I know. Moreover, `mypy` misses some hooks required for such plugin creation.
Does `pyright` handle it better?

**Comment by RobertCraigie** [comment]
If I'm understanding correctly, you're talking about a situation like this?


```py
import pytest

@pytest.fixture
def name() -> str:
    return 'Robert:


def test_name(name) -> None:
    # name is inferred to be str
    ...
```

If so that is sadly not possible with pyright. Fixtures have to be explicitly annotated:

```py
def test_name(name: str) -> str:
    ...
```

Pyright also doesn't have a plugin system so it wouldn't be possible to support something like that :(

It does however support recursive types and is considerably faster :)

**Comment by Tinche** [comment]
I think just annotating the fixture manually in the test is the way to go. The type checker would need to understand pytest's scoping rules, that just seems too much.

**Comment by asvetlov** [comment]
Manual annotations are what I have at my daily job (we have about 125000 lines of pytest-based tests).
Trivial fixtures are easy but fixture factories are tedious.
