### ISSUE TITLE
Complete move to pytest-dev

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest-asyncio#2]
Hi @Tinche,

I have set you up as owner of this repository, and a collaborator of @pytest-dev, so I think all is good. :smile:

To complete the transition, here are a couple of things it would be nice to do:

- [ ] Update links in code (`setup.py`, `README`, etc) and documentation;
- [ ] Update Travis connection;
- [ ] Update coveralls connection;

Feel free to ask for help with any of these, here or in the mailing list.

Welcome! :smile:

**Comment by GMLudo** [comment]
Congratulations @Tinche and @nicoddemus, it's good to see that this project becomes an official repository of `pytest` ;-)
