### ISSUE TITLE
plugin doesn't work together with `pytest-randomly`

### ISSUE THREAD

**Issue by skarzi** [pytest-dev/pytest-asyncio#202]
Hi :wave: 

first of all big thanks for this awesome plugin!

Recently I was writing tests for `django-channels` async consumers and middlewares. For writing these tests I am using also [`pytest-randomly`](https://github.com/pytest-dev/pytest-randomly) and `django-channel` [`InMemoryChannelLayer`](https://channels.readthedocs.io/en/stable/topics/channel_layers.html#in-memory-channel-layer).
When tests are running without `pytest-randomly` (with flag `-p no:randomly`) tests are passing, however with `pytest-randomly` plugin on I get exceptions like:

```
RuntimeError: Task <Task pending name='Task-49' coro=<InMemoryChannelLayer.receive() running at /usr/local/lib/python3.8/site-packages/channels/layers.py:250> cb=[_wait.<locals>._on_completion() at /usr/local/lib/python3.8/asyncio/tasks.py:515] created at /usr/local/lib/python3.8/site-packages/channels/utils.py:40> got Future <Future pending created at /usr/local/lib/python3.8/asyncio/base_events.py:422> attached to a different loop
```

When I add `event_loop` session-scoped fixture like suggested in https://github.com/pytest-dev/pytest-asyncio/issues/38#issuecomment-264418154 everything works like a charm even with `pytest-randomly`.

Do you have any idea why this is happening?

**Comment by Tinche** [comment]
It's probably interfering with the way we generate the event loop and initialize async fixtures. Feel free to poke around yourself and see if there's an easy fix :)

I would start by adding print statements to the existing request-scoped event loop fixture

**Comment by skarzi** [comment]
I managed to find the root of the issue, and it's not related to the `pytest-asyncio` ;) 
Basically, [`InMemoryChannelLayer`](https://channels.readthedocs.io/en/stable/topics/channel_layers.html#in-memory-channel-layer) is using [`random.choice()`](https://github.com/django/channels/blob/ece488b31b4e20a55e52948f21622da3e38223cb/channels/layers.py#L265) to generate new channels names, `pytest-randomly` is controlling [random seed for each test](https://github.com/pytest-dev/pytest-randomly/blob/5b374fde5593f547c3b77824eca3e4a461957192/src/pytest_randomly.py#L131), so it's common to get identical channel name for many tests and finally, channels aren't automatically [flushed](https://github.com/django/channels/blob/ece488b31b4e20a55e52948f21622da3e38223cb/channels/layers.py#L303) at the end of each test and this means that channels' `Queue`s are reused, but they were created/bound to the previous event loop, so `RuntimeError` is raised.
