### ISSUE TITLE
New warning triggered in v0.15.0 when using asyncio.ensure_future?

### ISSUE THREAD

**Issue by ondrej-ivanko** [pytest-dev/pytest-asyncio#217]
Hi,

I'm wondering what changed between version 0.14.0 and 0.15.0. I checked issues and merge requests mentioned in release notes for v 015.0 and couldn't find anything causing to raise afer-test warnings that did not appear when running tests 2 months back. I get these warnings:

```
uhura/tests/test_job/test_block.py::TestBlock::test_block_config_not_found
  /usr/local/lib/python3.9/asyncio/base_events.py:667: RuntimeWarning: coroutine 'SomeClass.inbox_in_loop' was never awaited
    self._ready.clear()

uhura/tests/test_job/test_block.py::TestBlock::test_block_config_not_found
  /usr/local/lib/python3.9/asyncio/base_events.py:667: RuntimeWarning: coroutine 'SomeClass.update_in_loop' was never awaited
    self._ready.clear()

uhura/tests/test_job/test_block.py::TestBlock::test_block_config_not_found
  /usr/local/lib/python3.9/asyncio/base_events.py:667: RuntimeWarning: coroutine 'SomeClass.dismiss_in_loop' was never awaited
    self._ready.clear()

-- Docs: https://docs.pytest.org/en/stable/warnings.html
====================================================================== 55 passed, 3 warnings in 0.89s =======================================================================
```

It looks like it's related to asyncio library, but contary to that I don' t get these warnings when running test with pytest-asyncio v0.14.0.

As you can see async functions <b>inbox/update/dismiss_in_loop</b> are raising warnings.

The tested code causing the warning looks like this:
```
class SomeClass(MetaClass):

    @classmethod
    def cls_init(cls, qfilter=None):
        if not qfilter:
            qfilter = qfilter_mu
        cls.inbox = OldRedisStreamQueue(cls.__name__ + "_inbox-0", qfilter)
        cls.update = asyncio.Queue(loop=loop)
        cls.dismiss = asyncio.Queue(loop=loop)
        asyncio.ensure_future(cls.inbox_in_loop())
        asyncio.ensure_future(cls.update_in_loop())
        asyncio.ensure_future(cls.dismiss_in_loop())
        SomeClass.objects[cls] = set()

----------------------------------

class MetaClass:

    @classmethod
    async def inbox_in_loop(cls):
        while True:
            await cls.inbox_in()

    @classmethod
    async def update_in_loop(cls):
        while True:
            await cls.inbox_in()    

    @classmethod
    async def dismiss_in_loop(cls):
        while True:
            await cls.inbox_in()    
```
As you can see inbox/update/dismiss_in_loops are coroutines returned as Task by ensure_future. We don't see same warnings in application logs in logger.

The event_loop is patch like this and inherited in every test module via Superclass.
```
@pytest.fixture(scope="function", autouse=True)
def patch_main_loop(self, mocker, event_loop):
    mocker.patch.object(main, "loop", event_loop)
```
loop is mocked with event_loop fixture on every single test run, which are marked with pytest.mark.asyncio.

The test are unfortunately too long and complicated to replicate them here.
Running:
Python version is 3.9.5, Linux Ubuntu 20.04

Solutions tried so far:
a) replacing asyncio.ensure_future with loop.create_task as it's recommended way of scheduling tasks since Py 3.7
b) trying run_in_executor, run_until_complete, asyncio.gather

My theory is some linter triggers warning because cls_init is sync function calling coroutine without await keyword. The absence of await keyword might the issue here confusing linter. It might be false negative.

**Comment by seifertm** [comment]
The `RuntimeWarning` is issued by the `asyncio` module in the standard library when an event loop is closed. It happens when you create a coroutine, but never schedule it to run using `await`. The following code demonstrates the warning:

```
import asyncio

async def my_coroutine():
    print("I was run")

async def main():
    my_coroutine()

asyncio.run(main())
```

If we change the call in `main` to `await my_coroutine()` or `asyncio.ensure_future(my_coroutine())`, no warning will show and the message will print as expected. That means your code somewhere creates coroutines and the event loop is closed without the coroutines being run/awaited.

Regarding the pytest-asyncio side: Starting from version 0.15 pytest-asyncio [closes the current loop, before replacing it with a new loop.](https://github.com/pytest-dev/pytest-asyncio/blob/740af1843f1dafb47ba6db236c1e354731993949/pytest_asyncio/plugin.py#L94-L96) That's why you don't see the same behaviour with pytest-asyncio 0.14.

Note that the pytest-asyncio's `event_loop` fixture and your `patch_main_loop` are function-scoped. Therefore, the event loop is closed after every test function. I assume that your test setup somehow outlives the function scope and the event loop gets closed in between tests by pytest-asyncio.

As a workaround, you could try expanding `event_loop` fixture to module scope and see if it helps. Or you could run your tests with the environment variable `PYTHONTRACEMALLOC=1` to find the exact code lines that create the coroutines.

Right now, I don't think this is a bug of pytest-asyncio. I am happy to take another look, if you can provide a code example that reproduces your problem, though.

**Comment by PushUpek** [comment]
I think that something is wrong...
pytest: 0.15.1

```
from asyncio import ensure_future
from unittest import mock

import pytest


class TestBug:
    def method(self):
        ensure_future(self.async_func())

    async def async_func(self):
        return None


@pytest.mark.asyncio
async def test_async_func():
    tf = TestBug()

    await tf.async_func()


@mock.patch.object(TestBug,
                   'async_func',
                   return_value=None,
                   new_callable=mock.AsyncMock)
def test_method(mock_async_func):
    tf = TestBug()

    tf.method()

    mock_async_func.assert_called_once()
```

and result is:
```
❯ pipenv run pytest test.py
========================================= test session starts ==========================================
platform darwin -- Python 3.9.6, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /private/tmp/test_fuck
plugins: asyncio-0.15.1
collected 2 items

test.py ..                                                                                       [100%]

========================================== 2 passed in 0.02s ===========================================
```

but if we change tests order like that:

```
from asyncio import ensure_future
from unittest import mock

import pytest


class TestBug:
    def method(self):
        ensure_future(self.async_func())

    async def async_func(self):
        return None


@mock.patch.object(TestBug,
                   'async_func',
                   return_value=None,
                   new_callable=mock.AsyncMock)
def test_method(mock_async_func):
    tf = TestBug()

    tf.method()

    mock_async_func.assert_called_once()


@pytest.mark.asyncio
async def test_async_func():
    tf = TestBug()

    await tf.async_func()
```

we will get warning:
```
❯ pipenv run pytest test.py
========================================= test session starts ==========================================
platform darwin -- Python 3.9.6, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /private/tmp/test_fuck
plugins: asyncio-0.15.1
collected 2 items

test.py ..                                                                                       [100%]

=========================================== warnings summary ===========================================
test.py::test_async_func
  /opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py:667: RuntimeWarning: coroutine 'AsyncMockMixin._execute_mock_call' was never awaited
    self._ready.clear()

-- Docs: https://docs.pytest.org/en/stable/warnings.html
===================================== 2 passed, 1 warning in 0.02s =====================================
```

**Comment by asvetlov** [comment]
@PushUpek in your example the warning source is a regular `def test_method(...):` test that is not handled by pytest-asyncio plugin.
