### ISSUE TITLE
Assertion details lost when using `pytest-asyncio`

### ISSUE THREAD

**Issue by WhyNotHugo** [pytest-dev/pytest-asyncio#218]
Take this example:

```
x = 1
y = 2
assert x = y
```

`pytest` expands the details on this failure and prints the values of both `x` and `y`.

However, when using `pytest-asyncio`, the output is just `AssertionError`:

```
================================================ FAILURES =================================================
_________________________ TestFilesystemStorage.test_metadata_normalization[None] _________________________
tests/storage/__init__.py:351: in test_metadata_normalization
    assert s.get_meta("displayname") == normalize_meta_value(value)
E   AssertionError
============================================ warnings summary =============================================

```

**Comment by WhyNotHugo** [comment]
So it's basically this pytest feature that stops working, "assertion introspection: https://docs.pytest.org/en/6.2.x/assert.html#assert

**Comment by asvetlov** [comment]
Sorry, I have no idea what is broken in your case.
Definitely, the problem is out of the project scope. pytest-asyncio doesn't implement pytest assertion hooks, it cannot break them.

**Comment by waza-ari** [comment]
Sorry for digging out this old thread, have you ever figured out what the problem was? I'm facing the same situation after migrating tests to pytest-asyncio, but truth be told, it's a somewhat obscure problem to track down...

**Comment by seifertm** [comment]
@waza-ari I cannot reproduce the issue based on the example of the OP.

Can you provide a minimal example that reproduces the issue?

**Comment by waza-ari** [comment]
@seifertm thanks for your prompt response - in this case it was a clear layer 8 problem. During the refactor I messed up my project layout a bit and changed the import mode to `importlib`:

```toml
[tool.pytest.ini_options]
asyncio_mode = "auto"
addopts = [
    "--import-mode=importlib",
]
```

Switching to default import mode (by simply removing the options) fixed the issue. Not a `pytest-asyncio` fault.
