### ISSUE TITLE
During cleanup, should pytest-asyncio cancel outstanding tasks, shut down async generators, and shut down the thread pool, like `asyncio.run()` does?

### ISSUE THREAD

**Issue by SyntaxColoring** [pytest-dev/pytest-asyncio#222]
Here's how `pytest-asyncio` implements the `event_loop` fixture:

https://github.com/pytest-dev/pytest-asyncio/blob/6ec76477061ea14394cadbf2cef673b04971ef4d/pytest_asyncio/plugin.py#L224-L229

Note that `loop.close()` is the sole cleanup code.

Compare this with [the implementation of `asyncio.run()`](https://github.com/python/cpython/blob/93d90871d216625b8d9db0fa59693953353d19ae/Lib/asyncio/runners.py#L39-L52):

```python
    loop = events.new_event_loop()
    try:
        events.set_event_loop(loop)
        if debug is not None:
            loop.set_debug(debug)
        return loop.run_until_complete(main)
    finally:
        try:
            _cancel_all_tasks(loop)
            loop.run_until_complete(loop.shutdown_asyncgens())
            loop.run_until_complete(loop.shutdown_default_executor())
        finally:
            events.set_event_loop(None)
            loop.close()
```

Before calling `loop.close()`, `asyncio.run()` does this:

1. It attempts to cancel outstanding tasks with `_cancel_all_tasks()`.
2. It calls `loop.shutdown_asyncgens()`
3. It calls `loop.shutdown_default_executor()`.

(I think (2) and (3) correspond to what [the documentation](https://docs.python.org/3/library/asyncio-task.html#asyncio.run) calls "finalizing asynchronous generators and closing the threadpool.")

I only have a tenuous grasp on these `asyncio` internals, but **it seems like the `event_loop` fixture should do this, too?** And so should any other place in `pytest-asyncio` where the event loop is shut down, if there are more.

**Comment by andyljones** [comment]
Echoing this - I just spent a while figuring out where the heck these 'async generator not closed' warnings were coming from in my test suite, when I couldn't reproduce the behaviour in prod.

**Comment by podusowski** [comment]
+1

Got a bunch of "Task was destroyed but it is pending!" because tasks weren't allowed to handle cancellation and finish.

**Comment by Tinche** [comment]
Yeah, this seems like a good change to make. I'll take a PR or implement this myself in the next couple of weeks.

**Comment by asvetlov** [comment]
Can be solved as a side-effect of https://github.com/pytest-dev/pytest-asyncio/issues/235
