### ISSUE TITLE
Using async in pyppeteer test, opened several browsers, but only the last one can run, the others fail to location.

### ISSUE THREAD

**Issue by heliping** [pytest-dev/pytest-asyncio#224]
I use pytest asyncio function with pyppeteer to test the web UI.

the testcase like this:
```
@pytest.mark.asyncio
async def test_lock_remote(): 
     await  xxxxxx

@pytest.mark.asyncio
async def test_lock_onsite(): 
      await xxxxxx

```
but the first case can be interrupt by the second one. and the second one can success, the first one always fails, and lost its mouse focus.

**Comment by AIGeneratedUsername** [comment]
@heliping Could you please add **pyppeteer**, **Python**, **pytest**, **pytest-asyncio** versions to your message?

**Comment by asvetlov** [comment]
Sorry, the bug report has no reproducible example.

**Comment by seifertm** [comment]
@heliping Judging from #91 pyppeteer uses asyncio tasks for clean up purposes. The default `event_loop` fixture of pytest-asyncio creates a new loop for each of your test cases. Issue #91 shows that this can cause the cleanup to fail in some cases. You can try using a session scoped `event_loop` fixture and see if it solves your problem:
```
@pytest.fixture(scope="session")
def event_loop():
    loop = asyncio.get_event_loop_policy().new_event_loop()
    yield loop
    loop.close()
```


As @AIGeneratedUsername and @asvetlov already mentioned we need more information to help you out. Feel free to reopen this issue, If you can provide a reproducible example.
