### ISSUE TITLE
Testing with a different event loops

### ISSUE THREAD

**Issue by aklajnert** [pytest-dev/pytest-asyncio#227]
I have a use case where I need to change the default event loop on Windows. The recommended approach is to override the `event_loop` fixture, which works fine.  
My problem is that I still want to test how my code works with another event loop (the real default, that is not my default).

There is no easy way to do that, I came up with a solution that is more a hack than something I'd like to have in my code:  
```python
@pytest.fixture(autouse=True)
def event_loop(request):
    if request.node.name.startswith("test_invalid_event_loop"):
        loop = asyncio.SelectorEventLoop()
    else:
        loop = asyncio.ProactorEventLoop()  # this loop is not a default before Python 3.8
    yield loop
    loop.close()
```

I could extract these tests to a separate file and just have a different `event_loop` fixture there, but it doesn't seem right either.

I see two solutions:
- Read the default event loop policy from `conftest.py` 
- Allow do define more `event_loop` fixtures by matching not a full fixture name, but checking if it ends with `event_loop`. It would be then possible to create and use `a_event_loop` and `b_event_loop`, etc.

**Comment by asvetlov** [comment]
I think the proposed approach is viable if splitting tests into multiple files is not an option.
`autouse=True` is not required though.

**Comment by aklajnert** [comment]
Do you mean that piece of code I've put into the issue or one of the solutions I've proposed below?  
My snippet is just an ugly hack and I believe that it can be done a bit better with one of the solutions I proposed.  
I can also try to submit a PR with the implementation for a chosen solution.

**Comment by asvetlov** [comment]
I mean `event_loop` defined in a test module.
```
def event_loop(request):
    if selector_loop_requested(request):  # can decide on request.node.name or whatever
        loop = asyncio.SelectorEventLoop()
    else:
        loop = asyncio.ProactorEventLoop()
    yield loop
    loop.close()
    ```
    
Anyway, there is no need to change the plugin code. Everything works already. 
Closing the issue.
