### ISSUE TITLE
release 0.16.0

### ISSUE THREAD

**Issue by DJRickyB** [pytest-dev/pytest-asyncio#229]
Hi! Can we anticipate a 3.10-compatible release of pytest-asyncio in the near future, given 3.10.0 released Oct 4th?

**Comment by Tinche** [comment]
Does the current release not work? I can get on this soon.

**Comment by DJRickyB** [comment]
well, it depends on your definition of "not working"...

Our CI fails due to the deprecation warnings fixed in #212.  The library works but we'd prefer not to support 3.10 until we can get clean CI, without ignoring warnings

**Comment by pquentin** [comment]
@Tinche Thanks a lot for the release! I work with @DJRickyB, and we now use pytest-asyncio 0.16.0.

This helped us notice that the deprecation warning were actually coming from our own tests, which makes sense as #212 only fixed deprecation in pytest-asyncio's test suite. So the release was not needed (sorry!), but did help us (thanks!).
