### ISSUE TITLE
helping the maintenance bus factor

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest-asyncio#232]
It seems that maintenance has come to a halt,
in this issue i want to prepare communicating current factors and/or enable a call for help

the goal being documenting the current state,
so people have a idea what to expect while the shortage of committable volunteer time means  less happens
as well as organizing additional volunteers that can help the process. 

CC @pytest-dev/pytest-asyncio-admin

**Comment by Tinche** [comment]
It's true, since my time is spread between a lot of other projects at this point I essentially only make sure this plugin works on new Pythons.

Note that I actively use the plugin on a daily basis, so despite the amount of issues I know the plugin actually works. But I would welcome some qualified help, of course.

**Comment by RonnyPfannschmidt** [comment]
@Tinche its great to know that you are indeed a regular user and the minimum is secured

as for qualified help - would it be ok if i did a call for help using the pytestorg twitter account nd may i mention you and/or would you like to do the call for help so we can add reach to it?

**Comment by Tinche** [comment]
Ugh I think if we do a call for help on Twitter we will get a ton of unqualified help, which will be even more work. Can we get some pytest folks in first? So maybe through the mailing list?

**Comment by RonnyPfannschmidt** [comment]
yes we can, i agree that the qualification filtering can be quite a pain

do you want to try to get something out to the pytest-dev ml or would you like for me to draft something up between the days

**Comment by Tinche** [comment]
Would appreciate assistance ;)

**Comment by RonnyPfannschmidt** [comment]
i'll spend time on this between christmas and the new year
i wont mind anyone beating me to it tho ;P

**Comment by RonnyPfannschmidt** [comment]
initial email to pytest-dev is out

**Comment by asvetlov** [comment]
Well, I can help with the maintenance.
I use pytest-asyncio at my daily job and maintain asyncio itself as a part of CPython.

**Comment by RonnyPfannschmidt** [comment]
@Tinche in addition to @asvetlov , @seifertm also reached out on the ml

i haven't yet found the time to look deeply into them, but at first glance it looks like both of them bring good experience

 do you already have some rough idea of them so we can cut it short, else i'll take a deeper look mid week (my initial impression is good)

**Comment by Tinche** [comment]
I would be very glad to have @asvetlov and @seifertm as fellow maintainers.

As a first step: do you folks have any PRs yourselves that I should review ASAP? If yes I will do so.

As a second step: I will defer to your judgement on what PRs to merge in and what issues to close/not close.

After a while when we've built up a working relationship, I'm happy giving you folks commit rights here on GitHub and co-ownership on PyPI.

**Comment by asvetlov** [comment]
I have no my PRs.
There is a pull request from @seifertm #192 which looks good to me.

**Comment by asvetlov** [comment]
Reviewed a bunch of existing PRs, skipped pull requests that are not bad for me but maybe should be fixed differently.

I would say that missing write access prevents me from trying to resolve merge conflicts on GitHub.

The next stage should be issue triaging.

**Comment by Tinche** [comment]
@asvetlov thank you very much with your help!

@nicoddemus can you add @asvetlov to the pytest-asyncio-admin group?

**Comment by nicoddemus** [comment]
> @nicoddemus can you add @asvetlov to the pytest-asyncio-admin group?

I can, but I made you maintainer of the team, please check if you can add @asvetlov yourself.

**Comment by Tinche** [comment]
@nicoddemus It says he's 'not a member of this organization'. Do we need to add him to pytest first?

**Comment by nicoddemus** [comment]
Hmm seems like it, sent an invitation:

![image](https://user-images.githubusercontent.com/1085180/148426826-8f914bb8-6dd2-4043-82cd-93b3c39cde82.png)

**Comment by Tinche** [comment]
@nicoddemus can you do the same for @seifertm please?

**Comment by RonnyPfannschmidt** [comment]
i did it

**Comment by asvetlov** [comment]
We can close it I guess.
