### ISSUE TITLE
Release 0.17

### ISSUE THREAD

**Issue by asvetlov** [pytest-dev/pytest-asyncio#248]
I think we handled all low-hanging fruits.

I suggest creating a new pytest-asyncio 0.17 release.

Later I want to continue my work on future improvements, but now we have important features implemented.

The release is crucial also as a part of the preparation for working pytest-asyncio and pytest-aiohttp together.
I need a new pytest-asyncio release to raise a warning by pytest-aiohttp if the calculated mode is *legacy* and rely on pytest-asyncio implementation for *auto* and *strict* modes.
Later I'll drop custom async tests and fixtures support from pytest-aiohttp entirely.

@Tinche I can setup auto-deployment on git tag publishing by GitHub actions if you agree with the idea.
For this, I need access to PyPI project for the plugin. My PyPI name is `andrew.svetlov`

**Comment by Tinche** [comment]
@asvetlov great, thanks so much. I agree with GitHub Actions, and I've invited you to be a co-owner on PyPI.

**Comment by seifertm** [comment]
Regarding automatic deployments: I just picked up #37 which intended include `setuptools_scm` to enable automatic deployments based on git tags. Is the PR still relevant for what you intend to do?

**Comment by asvetlov** [comment]
@seifertm great idea!
Declarative setup requires a slightly different configuration placed in `pyproject.toml`: https://github.com/pypa/setuptools_scm#pyprojecttoml-usage

Otherwise, I completely agree, SCM simplifies the release process a little.

**Comment by phlax** [comment]
probably an easyfix but the latest version is throwing an error in some of my tests

```console
INTERNALERROR> DeprecationWarning: The 'asyncio_mode' default value will change to 'strict' in future, please explicitly use 'asyncio_mode=strict' or 'asyncio_mode=auto' in pytest configuration file.
```

**Comment by phlax** [comment]
adding the config to pytest.ini fixed the problem, but im wondering why the default didnt work

**Comment by asvetlov** [comment]
@phlax correct

**Comment by asvetlov** [comment]
pytest-asyncio 0.17 is released

**Comment by Tinche** [comment]
Great job @asvetlov @seifertm !!

**Comment by asvetlov** [comment]
Thanks!
