### ISSUE TITLE
Update codecov/codecov-action to v2

### ISSUE THREAD

**Issue by seifertm** [pytest-dev/pytest-asyncio#249]
CI is currently using `codecov/codecov-action@v1` to upload coverage data. Version 1 of the GH action will [stop working at 2022-02-01](https://github.com/codecov/codecov-action/blob/260aa3b4b2f265b8578bc0e721e33ebf8ff53313/README.md).

We should upgrade to `codecov/codecov-action@v2`

**Comment by asvetlov** [comment]
Updated
