### ISSUE TITLE
Unclosed event loops warning from pytest-asyncio 0.17.0 on Windows

### ISSUE THREAD

**Issue by dvarrazzo** [pytest-dev/pytest-asyncio#256]
Hello,

after updating to pytest-asyncio 0.17.0, and setting `asyncio_mode=auto` in the config, we are seeing asyncio tests failing because warnings are generated on Windows.

See [this test run](https://github.com/psycopg/psycopg/runs/4805258822?check_suite_focus=true) for the errors.

Is there anything wrong we are doing or is it a regression? [This test configuration](https://github.com/psycopg/psycopg/blob/da482bf71627256b2565098f42d27ed382c7383c/tests/conftest.py#L65-L85) might be relevant.

Thank you very much

**Comment by asvetlov** [comment]
Hey!
Could you please call `asyncio.set_event_loop_policy()` and `uvloop.install()` outside of the `event_loop` fixture.
`@fixture(scope="session", autouse=True)` could be a good place for such things.

**Comment by dvarrazzo** [comment]
Almost! Setting up a session failed when [the first test of the run is async](https://github.com/psycopg/psycopg/actions/runs/1693694255) (tests run order is randomized). The direction was right though.

The problem is solved my moving the initialisation code into `pytest_sessionstart()` instead.

Thank you very much!

**Comment by asvetlov** [comment]
You are welcome!
Thank you for `psycopg3` BTW.
This project makes `aiopg` obsolete, we can archive it and suggest using the well-supported upstream :)
