### ISSUE TITLE
Tests don't fail anymore

### ISSUE THREAD

**Issue by a7p** [pytest-dev/pytest-asyncio#26]
having a minimal:
```
from pytest import mark
@mark.xfail(reason="I need a failing 
def test_fail_please():
     assert False

@mark.xfail(reason="I'm testing for a pytest-asyncio-bug - if I don't fail something is broken.")
@mark.asyncio
def test_fail_async():
     assert False
```

`test_fail_async` fails as expected with asyncio==0.3.0, but succeeds with asyncio==0.4.0.

(running python3.5.1)

**Comment by Tinche** [comment]
Hi, thanks for reporting, it's a known issue: #25. Expect a new release later today :)

**Comment by a7p** [comment]
arg - the title did not make me look at the issue ;).

**Comment by Tinche** [comment]
Hi, I've just pushed 0.4.1 to PyPI. Can you confirm it fixes the issue for you?

**Comment by a7p** [comment]
thank you very much - it does.
