### ISSUE TITLE
0.17.* issues with tornado loop started by dask distributed

### ISSUE THREAD

**Issue by bphillips-exos** [pytest-dev/pytest-asyncio#271]
Hello, the following test fails on teardown. I believe this is due to the tornado IOLoop that is started when the cluster is initialized. This example works on 0.16.0 and fails when upgrading to 0.17.0+. 

```python3
from dask.distributed import LocalCluster

@pytest.mark.asyncio
async def test_dask() -> None:
    cluster = LocalCluster()
```

```
tests/compute/test_cluster.py:20 (test_dask)
fixturedef = <FixtureDef argname='event_loop' scope='function' baseid=''>
request = <SubRequest 'event_loop' for <Function test_dask>>

    @pytest.hookimpl(trylast=True)
    def pytest_fixture_post_finalizer(fixturedef: FixtureDef, request: SubRequest) -> None:
        """Called after fixture teardown"""
        if fixturedef.argname == "event_loop":
            policy = asyncio.get_event_loop_policy()
            try:
                loop = policy.get_event_loop()
            except RuntimeError:
                loop = None
            if loop is not None:
                # Clean up existing loop to avoid ResourceWarnings
>               loop.close()

.venv/lib/python3.9/site-packages/pytest_asyncio/plugin.py:269: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/unix_events.py:58: in close
    super().close()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <_UnixSelectorEventLoop running=True closed=False debug=False>

    def close(self):
        if self.is_running():
>           raise RuntimeError("Cannot close a running event loop")
E           RuntimeError: Cannot close a running event loop

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py:89: RuntimeError
```

Versions: (reproduced on multiple versions of dask / distributed)
* dask 2022.1.0
* distributed 2022.1.0
* pytest 6.2.5
* pytest-asyncio 0.17.2

**Comment by bphillips-exos** [comment]
I traced the issue to this [change](https://github.com/pytest-dev/pytest-asyncio/commit/a6758a1c55c71e2a229905ee1b2ba9d7e8010b69) and confirmed that this [update](https://github.com/pytest-dev/pytest-asyncio/commit/0a3328f5fced1568b60fdd33e66937b7bbca8922) does not resolve.

**Comment by asvetlov** [comment]
I don't see a source code but looking at the reported error I can suggest that *function-scope* (default) `event_loop` fixture was used.
The *session-scoped* loop probably can solve the issue.

**Comment by bphillips-exos** [comment]
Hi @asvetlov, there is source code to reproduce in the first code block. Using a session scoped loop did indeed solve the issue.

**Comment by asvetlov** [comment]
Awesome! Closing, the session-scope `event-_loop` is the solution.
