### ISSUE TITLE
No version bump to 0.4.1?

### ISSUE THREAD

**Issue by Jenselme** [pytest-dev/pytest-asyncio#28]
Hi,

I see that there is a 0.4.1 version on [pypi](https://pypi.python.org/pypi/pytest-asyncio) but the code here on GitHub is still on version 0.4.0. Can you publish the commit for 0.4.1? I am asking this because I am maintaining this package for fedora and I use the source from GitHub and I would like to update it to 0.4.1.

**Comment by Tinche** [comment]
Ha, good catch. I just forgot, apologies. It's up now.

**Comment by Jenselme** [comment]
No problem. Thanks for the quick response time.
