### ISSUE TITLE
[TODO] Complete the configuration GHA+check+branch protection

### ISSUE THREAD

**Issue by webknjaz** [pytest-dev/pytest-asyncio#281]
I see that the workflow uses my `alls-green` action. It is primarily designed to be used as a single check added to the branch protection. Looks like this part has been forgotten — I haven't seen the respective job being marked as `Required`.
So I'm logging this issue/task for somebody to finish the repository settings setup.

**Comment by asvetlov** [comment]
The branch protection rules are set up.
Thanks for the reminder!
