### ISSUE TITLE
Does marking tests with pytest.mark.asyncio() runs all the tests asynchronously?

### ISSUE THREAD

**Issue by pawamoy** [pytest-dev/pytest-asyncio#296]
I recently showed a colleague how to write tests with temporary folders for ASGI applications, and suddenly I wondered how my async tests even worked.

Basically, I have a `client` fixture that will monkeypatch an attribute in my ASGI app, which is global, to use a temporary folder for each test.

It seems to work, so I guess that, even if I mark my tests with `pytest.mark.asyncio()`, they actually run sequentially (one test after the other) and not asynchronously (multiple tests overlapping) within the same process? And that the marker simply enables the use of `async def` and `await` in the test function's body?

Otherwise my tests simply wouldn't work because I'm monkeypatching a global variable!

For my sanity of mind, could you confirm that the marker only enables the use of `async`/`await` and does not actually tell pytest to run all tests within a process asynchronously 😅 ?

Thanks for the project by the way, it's really useful!

**Comment by Tinche** [comment]
Correct, they don't run concurrently. It just enables the machinery that sets up the event loop and awaits the test.

**Comment by pawamoy** [comment]
Great, thanks 😄
