### ISSUE TITLE
pytest-asyncio doesn't work with trio fixtures

### ISSUE THREAD

**Issue by flolf** [pytest-dev/pytest-asyncio#298]
My `pytest.ini` file contains the following:
```
asyncio_mode = strict
```

I have the following fixture
```
@pytest_trio.trio_fixture
async def a_fixture():
    async with trio_asyncio.open_loop():
        ...
```

And the following test:
```
@pytest.mark.trio
async def test_something(a_fixture):
    ...
```

Unfortunately the `pytest` collection fails at the fixture level:
```
/mnt/harmonix_vol2/soporifix_vol3/user/home/atl/ops3venv8_1/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
/mnt/harmonix_vol2/soporifix_vol3/user/home/atl/ops3venv8_1/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/mnt/harmonix_vol2/soporifix_vol3/user/home/atl/ops3venv8_1/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
/mnt/harmonix_vol2/soporifix_vol3/user/home/atl/ops3venv8_1/lib/python3.8/site-packages/pytest_asyncio/plugin.py:327: in pytest_pycollect_makeitem
    _preprocess_async_fixtures(collector.config, _HOLDER)
/mnt/harmonix_vol2/soporifix_vol3/user/home/atl/ops3venv8_1/lib/python3.8/site-packages/pytest_asyncio/plugin.py:244: in _preprocess_async_fixtures
    assert _has_explicit_asyncio_mark(fixturedef.func)
E   AssertionError: assert False
E    +  where False = _has_explicit_asyncio_mark(<function server_client at 0x7f0ef019ff70>)
```

Why is pytest-asyncio not recognising the trio fixture?

**Comment by asvetlov** [comment]
pytest-asyncio bug

**Comment by seifertm** [comment]
I came up with a possible fix (see [this branch](https://github.com/seifertm/pytest-asyncio/tree/trio-fixture-compatibilty)), but the corresponding test is still failing on Python 3.7.

I got in touch with pytest-trio to figure out the issue (see https://github.com/python-trio/pytest-trio/issues/126)

**Comment by seifertm** [comment]
@flolf Can you please test again, if the latest state of master fixes your problem?
`pip install --upgrade git+https://github.com/pytest-dev/pytest-asyncio.git`

**Comment by aqc-carlodri** [comment]
Just stumbled into this issue and yes @seifertm I can confirm that `pytest-asyncio-0.18.3.dev3+gf979af9` fixes the problem! Thank you! Is there a timeline for an official release including this fix?

**Comment by seifertm** [comment]
@aqc-carlodri Thanks for the feedback!
If it fixes the issue, we can do a release right now.

**Comment by aqc-carlodri** [comment]
sounds great thank you!

**Comment by seifertm** [comment]
@aqc-carlodri pytest-asyncio-0.18.3 is now available on PyPI
