### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by hynek** [pytest-dev/pytest-asyncio#31]
An upgrade to 0.4.1 broke all my tests and I’m unable to locate some kind of changelog that could give me cues what’s going wrong…could you start keeping one please? :)

**Comment by Tinche** [comment]
Agreed, the project has become big enough to need one. I'll put one together before the next release.

Sorry for the breakage :)

**Comment by Tinche** [comment]
A simple changelog is up.

**Comment by Tinche** [comment]
Ping? Please close this issue if the changelog is acceptable. :)

**Comment by hynek** [comment]
oh yeah thanks, good enough :)
