### ISSUE TITLE
```RuntimeError: Event loop is closed``` after 0.17.0

### ISSUE THREAD

**Issue by dynalz** [pytest-dev/pytest-asyncio#310]
I have a big application which makes use of the same event_loop. 
For re-useability I share this LOOP between all services running on the same instance.

Before 0.17.0, I used to override the event_loop fixture, to just yield MY_GLOBAL_LOOP and never close it. 
After 0.17.0, it seems this is ignored somehow and something is forcing .close() on this loop producing:
```
RuntimeError: Event loop is closed
``` 
on all tests other than the 1st (which is successful)

My tests have the following snippet code:
```
from services import MY_GLOBAL_LOOP

@pytest.fixture
def event_loop():
    yield MY_GLOBAL_LOOP
```

**Comment by seifertm** [comment]
Thanks for reaching out!
I remember a user with a similar issue: #274

pytest-asyncio tries to run each test in a fresh event loop to prevent unwanted side effects. If your tests require that a single event loop is used for the whole test suite, you can try to extend the scope of the `event_loop` fixture to the whole test session:
```
@pytest.fixture(scope="session")
def event_loop():
    …
```
That way, the event loop will be reused for all tests in your test run.

Does that solve your issue?

**Comment by dynalz** [comment]
It solved!

Thanks
