### ISSUE TITLE
nobody else of pytest-dev is allowed to upload releases

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest-asyncio#33]
while discussiong pytest-dev/pytest#1793 i noticed that there is only one person allowed to do pypi upload,

it would be nice to add a few more of the core pytest-dev team to the pypi maintainers

**Comment by Tinche** [comment]
Sure, can you give me a list of a few core pytest dev's usernames on PyPI? I can add them.

**Comment by Tinche** [comment]
I've added hpk and nicoddemus as owners on PyPI.

@nicoddemus @hpk42

**Comment by nicoddemus** [comment]
:+1: thanks
