### ISSUE TITLE
0.18.3 doesn't wait for async fixtures

### ISSUE THREAD

**Issue by jjaanila** [pytest-dev/pytest-asyncio#338]
It seems that 0.18.3 introduces a bug(?) where async fixtures are not waited and they pass an async_generator to test cases instead of the yielded value. 0.18.2 works as described in documentation.

```python
class TestFixture:
    @pytest_asyncio.fixture
    async def some_async_fixture(self):
        await asyncio.sleep(10)
        yield "test"

    @pytest.mark.asyncio
    async def test_fixture(self, some_async_fixture):
        print(some_async_fixture)
```

With the code above and Python 3.10.4, pytest-asyncio 0.18.3 and pytest 6.2.5, the test run doesn't wait at all and prints:
`<async_generator object TestFixture.some_async_fixture at 0x7f7a552090c0>`

With Python 3.10.4, pytest-asyncio 0.18.2 and pytest 6.2.5, the run waits for 10s and prints:
`test`

I think this is probably a bug or then the documentation requires updating. I might have also misunderstood something. In the last case, please advice :)

**Comment by seifertm** [comment]
This is interesting, thanks for the report!

I cannot reproduce the issue on my machine, though. I tried reproducing the issue using the exact same versions of CPython, pytest-asyncio (v0.18.3), and pytest. Your code always prints "test" and runs for just over 10 seconds regardless of the my setting of `asyncio_mode`.

```
$ pytest -s --asyncio-mode=auto
==== test session starts ====
platform linux -- Python 3.10.4, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /tmp/test_pytest_aio
plugins: asyncio-0.18.3
asyncio: mode=auto
collected 1 item                                                                                                                    

test_a.py test
.

==== 1 passed in 10.02s ===
$ pytest -s --asyncio-mode=strict
==== test session starts ====
platform linux -- Python 3.10.4, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /tmp/test_pytest_aio
plugins: asyncio-0.18.3
asyncio: mode=strict
collected 1 item                                                                                                                    

test_a.py test
.

==== 1 passed in 10.02s ====
$ pytest -s --asyncio-mode=legacy
==== test session starts ====
platform linux -- Python 3.10.4, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /tmp/test_pytest_aio
plugins: asyncio-0.18.3
asyncio: mode=legacy
collected 1 item                                                                                                                    

test_a.py test
.

==== warnings summary ====
[…]
==== 1 passed, 1 warning in 10.02s ====
```

There's a chance the behaviour might be different based on the operating system. CPython uses a different default event loop implementation on Windows, for example. I ran the tests on Linux. Which OS are you experiencing the issues with?

**Comment by jjaanila** [comment]
I run tests with Ubuntu 20.04.4 and CPython. My colleagues ran into similar issues with Macs but they haven't tested 0.18.2 yet. I will post the results tomorrow.

**Comment by jjaanila** [comment]
The fix works also on Mac, so the issue has been resolved. Sorry for bothering you!

**Comment by seifertm** [comment]
@jjaanila No worries. I'm happy you could solve it. I like these kinds of issues much more than actual bugs :)
