### ISSUE TITLE
event_loop fixture not properly applied when pytest is called from outside of the directory without args

### ISSUE THREAD

**Issue by erny** [pytest-dev/pytest-asyncio#349]
## Problem description

- When I run: `pytest tests` everything works as expected
- When I run: `pytest`  without arguments, I get `RuntimeError: Event loop is closed` for all tests that use asyncio

(Sorry if this question was already resolved in another issue. I had a look but couldn't find a match.)

## Environment

* python 3.8.10 / Linux 5.4.0-110-generic / Ubuntu 18.04 / 64 bits
* pytest==7.1.2, pytest-asyncio==0.18.3, pytest-cov==2.12.1
* fastapi with mongodb (motor)

## Directory structure

```
.
├── main-package-dir
├── tests
│   ├── conftest.py
│   ├── test_example1.py
│   ├── test_example2.py

```
The `tests` directory has no `__init__.py`.

## `tests/conftest.py`

``` python
import asyncio
import pytest


@pytest.fixture(scope="session", autouse=True)
def event_loop():
    loop = asyncio.get_event_loop()
    yield loop
    # cancel pending tasks before shut down
    for task in asyncio.all_tasks(loop):
        if task != asyncio.current_task(loop):
            try:
                task.cancel()
            except asyncio.exceptions.CancelledError:
                pass
```

##  test_example*.py

This is a mix of normal and async tests with normal fixtures.

## Comments

I was trying to create a minimal example that fails, but wasn't still able to do it.

**Comment by seifertm** [comment]
Thanks for the report, this is sounds very weird indeed.

I assume there's a bad interaction with motor. At some point motor is creating a new event loop, even though it should reuse the one provided by pytest-asyncio. This would result in a RuntimeError when tearing down the event_loop fixture.

I dimly remember a mention of a similar error in another project, but I couldn't seem to find it, sorry… They tracked the down to being a setup issue, not a pytest-asyncio bug.

Maybe pytest-asyncio can provide a helpful warning or error message for the user. Can you provide a stack trace of the error so we can see where the RuntimeError is raised exactly? I could help debugging, if you manage to provide a reproducible example, but I won't be able to look into this in detail before Friday.

**Comment by seifertm** [comment]
As mentioned in my last post, we'd need a reproducible example to look into this issue.

@erny Any updates on this?

**Comment by seifertm** [comment]
@erny Did you manage to solve the issue in the meantime?

**Comment by erny** [comment]
Thanks for reaching out again, sorry, I had not much time to check this out. As it works, specifying explicitly the "test" directory, it is not so urgente. I'll close it in the meanwhile due to missing activity. Thanks for your support. BR.

**Comment by erny** [comment]
Thanks for your quick response.
The first thing: consider this issue as low priority.

The second thing: the issue is about the difference of invoking "pytest"
with or without argument, i.e. it may be a pytest issue, not of
pytest-asyncio. It's like the event_loop (in contest.py) is not applied at
the correct moment. I don't know what difference it makes in fixture
provisioning for both cases.

I'll try to get a clearer understanding of what is happening. Regards.

**Comment by seifertm** [comment]
@erny if you suspect a problem with the fixture setup, you can try adding the `--setup-show` command-line option to pytest. It will print when a specific fixture is setup up and torn down. You can test your theory by comparing the different pytest runs.
