### ISSUE TITLE
RuntimeError: Cannot run the event loop while another loop is running

### ISSUE THREAD

**Issue by baiyyee** [pytest-dev/pytest-asyncio#359]
When trying to do UI automtion with pytest-asyncio and pytest-playwright, I got exception like: **RuntimeError: Cannot run the event loop while another loop is running**

**Code structure:**
```
ui2/conftest.py
ui2/test_bing.py
```

**ui2/conftest.py**

```
import pytest
import asyncio


@pytest.fixture(scope="session")
def event_loop():
    """重写event_loop"""

    loop = asyncio.get_event_loop()
    yield loop
    loop.close()
```

**ui2/test_bing.py**

```
import pytest

from playwright.async_api import Page


@pytest.mark.asyncio
async def test_bing(page: Page):
    await page.goto("http://www.bing.com")
```

**env:**
```
pytest==7.1.2
pytest-asyncio==0.18.3
pytest-playwright==0.3.0
```

**Detail exception as below:**

![image](https://user-images.githubusercontent.com/4414171/170166462-f3ffd79f-fdde-47ee-a73a-c8b0585642a1.png)

**Comment by seifertm** [comment]
Thank you for the report and the example. Unfortunately, I will not have time to look into this for the next two weeks. If nobody else is going to pick this up, it'll have to wait until then.

**Comment by graingert** [comment]
one issue here is that you're expecting an async_api.Page, but pytest-playright uses the sync_api.Page https://github.com/microsoft/playwright-pytest/blob/456f8286f09f132d2e21f6bf71f27465e71ba17a/pytest_playwright/pytest_playwright.py#L22

```python
import pytest

from playwright.async_api import Page


@pytest.mark.asyncio
async def test_bing(page: Page):
    await page.goto("http://www.bing.com/")
```

**Comment by SilenceHe** [comment]
> 

so async api is not supported in pytest-playright?

**Comment by seifertm** [comment]
@graingert Thanks for jumping in!

As  mentioned _playwright-pytest_ only supports the synchronous Playwright API at the moment (see https://github.com/microsoft/playwright-pytest/issues/74).

@SilenceHe [This comment](https://github.com/microsoft/playwright-pytest/issues/74#issuecomment-916001720) in particular state that only `playwright.sync_api` is supported by _playwright-pytest_ and links to a `conftest.py` that allows the asynchronous API to be used.

**Comment by seifertm** [comment]
I didn't know about nest_asyncio. The project seems to solve the same problem as https://github.com/aio-libs/aioloop-proxy for which a draft PR exists (https://github.com/pytest-dev/pytest-asyncio/pull/312). 

@PeterStolz Your error message is similar to that of the OP. I see your problem as a different one, though, because it has nothing to do with playwright-pytest. Do you mind opening a separate issue for your? It would be very helpful if you could explain your use case a bit more.

CC @asvetlov It seems that nest_asyncio and aioloop-proxy do pretty much the same.

**Comment by seifertm** [comment]
Closing this issue as this doesn't seem to be a pytest-asyncio bug. Feel free to reopen, especially if there is anything we can do to improve support for playwright-pytest.
