### ISSUE TITLE
pytest.mark.asyncio with pytest.mark.parametrize  may break async 

### ISSUE THREAD

**Issue by SamShao-crypto** [pytest-dev/pytest-asyncio#379]
when i use pytest.mark.asyncio with pytest.mark.parametrize，the async logic break

**Comment by SamShao-crypto** [comment]
- [ ]
<img width="980" alt="Screen Shot 2022-07-01 at 12 16 50 PM" src="https://user-images.githubusercontent.com/107017136/176822420-84ae3f7a-1edb-4434-9423-887ea87c1911.png">

**Comment by SamShao-crypto** [comment]
total exhaust 6 sec，but expected lower than 6 （which is the time spending for serial）

**Comment by seifertm** [comment]
This is the expected behavior. pytest-asyncio creates a synchronous wrapper function for each async test case. The tests do not run concurrently.

There's an existing feature request for tests that run concurrently. I'll close this in favor of #69. Feel free to continue the discussion there.
