### ISSUE TITLE
pytest_fixture_setup hook must not return output as its hookspec is marked with `firstresult=True`

### ISSUE THREAD

**Issue by malinoff** [pytest-dev/pytest-asyncio#39]
From pluggy docs,
```
If firstresult is True the 1:N hook call (N being the number of registered
hook implementation functions) will stop at I<=N when the I'th function
returns a non-None result.
```
https://github.com/pytest-dev/pytest/blob/master/_pytest/vendored_packages/pluggy.py#L89-L97

**Comment by Tinche** [comment]
Our pytest_fixture_setup is actually a hookwrapper, but it's true we shouldn't return anything from it.

From the pytest docs:

> Note that hook wrappers don’t return results themselves, they merely perform tracing or other side effects around the actual hook implementations.

The tests seem to pass without a return, so I'll remove it.
