### ISSUE TITLE
Intercompatibiility among pytest-asyncio versions for pytest-plugins

### ISSUE THREAD

**Issue by DanCardin** [pytest-dev/pytest-asyncio#399]
I'm trying to debug some new test failures in a pytest-plugin (or two) we've written which can produce async fixtures

The two plugins are: https://github.com/schireson/pytest-mock-resources and https://github.com/schireson/pytest-alembic.

In particular, if you were to clone `pytest-alembic`, install dependencies, then upgrade `pytest-asyncio` to 0.17.0, you'd notice issues with the event_loop not running; then upgrade to either 0.18 or 0.19, and in either case you'll encounter `AttributeError: 'async_generator' object has no attribute 'dialect'`. Specifically [this test](https://github.com/schireson/pytest-alembic/blob/main/examples/test_async_sqlalchemy_native/conftest.py)

I would have expected setting asyncio_mode to `legacy` to at least temporarily solve the problem and produce behavior equivalent to 0.16, but it doesn't.

Going off the many prior bug reports relating to this problem, I'd think altering the source definition of `create_postgres_fixture`, defined [here](https://github.com/schireson/pytest-mock-resources/blob/main/src/pytest_mock_resources/fixture/database/relational/postgresql.py#L100) to use `pytest_asyncio.fixture` would fix the problem; but it doesn't.

---

When setting breakpoints inside pytest-asyncio, during the previously linked failing test, i notice that I never see the `async def` version of the `alembic_engine` definition provided in the [previously linked conftest](https://github.com/schireson/pytest-alembic/blob/main/examples/test_async_sqlalchemy_native/conftest.py), rather it only ever yields the [default, synchronous one](https://github.com/schireson/pytest-alembic/blob/main/src/pytest_alembic/plugin/fixtures.py#L122). 

This makes me wonder if there were some internal changes to the collection mechanism or something here, beyond just the stricter mode? Because it's clearly picking it up in the "legacy" mode used in 0.16, but is also clearly not detecting the fixture as being async beyond 0.16.

---
I tried reproducing some of this behavior, in fixtures which approximate what's going on in at least pytest-mock-resources:

```
import pytest
import pytest_asyncio


def create_fixture():
    async def foo():
        yield 4

    foo._force_asyncio_fixture = True
    return pytest.fixture(foo)


bar = create_fixture()


def test_bar(bar):
    assert bar == 4
    assert False
```

But this works just fine, so i'm somewhat at a loss of what could be going on here.

**Comment by DanCardin** [comment]
After some more sleuthing, it seems like there were at least two problems. In newer versions, `pytest-mock-resources` needed to be using `pytest_asyncio.fixture` in order to work in strict mode, this was more obvious and has been fixed.

What's less obvious is that `pytest-alembic` continues to exhibit the same behavior regardless. It's perhaps important to note that it generates additional tests and injects them into the set of tests being run, when run with `--test-alembic`. 

However, if you (as a consumer of the library) `from pytest_alembic.tests import test_upgrade` somewhere in your tests, it appears to work as intended.

So it seems like there's something incompatible about the way that it is either adding or generating the test items, introduced somewhere between 0.16 and 0.19 (i encounter other issues on 0.17 at least); although i've stepped through any relevant sounding commits and don't see anything that changed which seems like i might have affected this.

**Comment by seifertm** [comment]
This is more on gut feeling rather than me actually knowing what causes the issue…

But d8efa640f0aa1ba8856b908ba486150588018209 introduced a function called `_preprocess_async_fixtures` which evaluates fixtures. It is called in [pytest_pycollect_makeitem](https://github.com/pytest-dev/pytest-asyncio/blob/v0.19.0/pytest_asyncio/plugin.py#L326), whereas pytest-alembic [uses pytest hooks](https://github.com/schireson/pytest-alembic/blob/163949c2c295c1b1159f42c4baae63f0ad571c7e/src/pytest_alembic/plugin/hooks.py#L56-L67) that are called at later stages.

`_preprocess_async_fixtures` was introduced in v0.18. Is it possible that this is causing the problem you're seeing?

**Comment by DanCardin** [comment]
mmm, thanks for pointing out that commit for me, i suppose i must have glossed over the removal of logic from `pytest_fixture_post_finalizer`, which is definitley going to be why it no longer resolves. I'll close the issue now, as support is definitely going to require changes on pytest-alembic's side.

 I've started drafting changes to pytest-alembic to produce tests in a hopefully more natural way, such that it gets picked up here.
