### ISSUE TITLE
async generators pytest fixtures

### ISSUE THREAD

**Issue by sashgorokhov** [pytest-dev/pytest-asyncio#41]
Python 3.6 have introduced new async generator entity:
```python
async def foo():
    yield 'Foo'
```

When trying to create yield fixture in pytest (or a simple fixture but with `async def`) and decorate it  with `@pytest.mark.asyncio` i receive a `coroutine` instead of fixture result. 

Is there a way to make `pytest.mark.asyncio` recognize fixtures as coroutine functions or async generator functions and behave properly on them?

**Comment by Tinche** [comment]
Well, coroutine fixtures don't work at all currently, so neither do coroutine yield fixtures. :)

There's some work in a branch (https://github.com/pytest-dev/pytest-asyncio/tree/feature/async_fixtures) but I'm not really satisfied with the API as of yet, so it's a work in progress.

**Comment by Tinche** [comment]
This should work now!

**Comment by toriningen** [comment]
Awesome!

**Comment by franz-see** [comment]
Seems to be broken again
