### ISSUE TITLE
@mock.patch decorator doesnt work properly with @pytest.mark.asyncio

### ISSUE THREAD

**Issue by sashgorokhov** [pytest-dev/pytest-asyncio#42]
Sample test code:

`tests.py`
```python
from unittest import mock

import pytest
import testmodule


@pytest.mark.asyncio
async def test_async_mock_patch_contextmanager():
    with mock.patch('testmodule.foo') as foo_mock:
        assert testmodule.foo is foo_mock


@pytest.mark.asyncio
@mock.patch('testmodule.foo')
async def test_async_mock_patch_decorator(foo_mock):
    assert testmodule.foo is foo_mock  # FAILS


def test_mock_patch_contextmanager():
    with mock.patch('testmodule.foo') as foo_mock:
        assert testmodule.foo is foo_mock


@mock.patch('testmodule.foo')
def test_mock_patch_decorator(foo_mock):
    assert testmodule.foo is foo_mock
```

`testmodule.py`
```python
def foo():
    return 'Bar'
```

`test_async_mock_patch_decorator` will fail, because `testmodule.foo` is `<function foo at ###>`, not `<MagicMock name='foo' id='###'>`

Tested this on python3.6 only.

UPDATE:

Seems that on python `3.5.2` there is no such bug. All tests succeeded.

**Comment by nicoddemus** [comment]
It is kind of tricky to use `@mock.patch` with pytest because the order of the decorators matter, although I suppose it can be fixed.

Alternatively, you could use [pytest-mock](https://github.com/pytest-dev/pytest-mock) for your mocking needs. 😉

**Comment by sashgorokhov** [comment]
```python
@mock.patch('testmodule.foo')
@pytest.mark.asyncio
async def test_async_mock_patch_decorator(foo_mock):
    assert testmodule.foo is foo_mock
```

Fails as well. 
This bug seems interesting to me. Maybe I could try to fix it?

**Comment by Tinche** [comment]
By all means, feel free to play around :)

**Comment by sashgorokhov** [comment]
Seems like the problem here is in `mock.patch` itself, not `pytest-asyncio`. 
See Martiusweb/asynctest#5 for details. The package `asynctest` provides a fixed implementation of `mock.patch` which works just fine and above tests are passing with it.

I am closing this issue since it is not `pytest-asyncio` issue.

**Comment by JackLeo** [comment]
is there anything done with `mock.patch`?

**Comment by asvetlov** [comment]
Use `pytest-mock` instead or `with mock.patch():`.
`@mock.patch` is ugly, sorry.

**Comment by tupui** [comment]
As there is no issue with a context manager, an alternative to `pytest-mock` is to have a fixture which yield the context manager. See here on [SO](https://stackoverflow.com/a/59045506/6522112) for ref:

```python
@pytest.fixture()
def mocked_worker():
    with patch('test.test_module.os.getcwd', return_value="Testing"):
        result = Worker()
        yield result
```
