### ISSUE TITLE
DeprecationWarning for pytest <7 is emitted on 0.20 with `pytest >= 7`

### ISSUE THREAD

**Issue by flaeppe** [pytest-dev/pytest-asyncio#430]
Seems that #420 adds a check for:

```python
if getattr(pytest, "__version_tuple__", (0, 0, 0) < (7,)):
    ...
```

Although that module has no `__version_tuple__` attribute, so the fallback value is used:

```console
python -c "import pytest; pytest.__version_tuple__"
```

Raises:

```
AttributeError: module pytest has no attribute __version_tuple__. Did you mean: 'version_tuple'?
```

---

```console
$ pytest --version
>>> pytest 7.1.3
```

**Comment by seifertm** [comment]
@flaeppe Thanks for the report. Can you verify if the patch provided in #431 works for you?

**Comment by seifertm** [comment]
You can install the patch with the command:
`$ pip install --upgrade git+https://github.com/seifertm/pytest-asyncio@silence-deprecation-warning-when-using-pytest-7`

**Comment by flaeppe** [comment]
It works. Thanks for the fast resolution
