### ISSUE TITLE
Python 3.10.9: DeprecationWarning: There is no current event loop

### ISSUE THREAD

**Issue by jakob-keller** [pytest-dev/pytest-asyncio#460]
CPython 3.10.9 was [released this week](https://docs.python.org/release/3.10.9/whatsnew/changelog.html#python-3-10-9-final) and tweaked the DeprecationWarning of [asyncio.get_event_loop()](https://docs.python.org/release/3.10.9/library/asyncio-eventloop.html#asyncio.get_event_loop): https://github.com/python/cpython/issues/93453

As a consequence tests are now failing again, despite #214.

**Comment by seifertm** [comment]
Thanks for reporting this.

The DeprecationWarning is triggered by [pytest_fixture_setup](https://github.com/pytest-dev/pytest-asyncio/blob/v0.20.2/pytest_asyncio/plugin.py#L404). Apparently, pytest-asyncio tries to clean any existing event loop and replace the current loop with the one provided by the _event_loop_ fixture. This means the warning is triggered every time pytest-asyncio is used. As a result, users receive a DeprecationWarning for one of their test dependencies. This can break their tests, if they use `-W error`.

Pytest-asyncio tries to close any unclosed event loop before running a test. This is convenient for the user, but it means that users don't notice faulty event loop handling in their code. If users need to work with event loops they should also take care to dispose them properly. Pytest-asyncio should not try to be smarter and do it for them.

In my opinion the correct solution is to raise a warning or an error when the user tries to use pytest-asyncio with a running or unclosed event loop. However, this would be a breaking change and I prefer to address this issue in a patch release.

To avoid having to deal with unnecessary DeprecationWarnings, my suggestion is to simply ignore the warnings, until we implement the breaking change mentioned above.

**Comment by jakob-keller** [comment]
> To avoid having to deal with unnecessary DeprecationWarnings, my suggestion is to simply ignore the warnings, until we implement the breaking change mentioned above.

I have done this and it works like a charm, at least until we migrate to Python 3.12.

**Comment by seifertm** [comment]
You're welcome. I bet this affects a lot of users.

I'll reopen the issue, because I we need to find a permanent solution that doesn't break in Python 3.12.

**Comment by nolar** [comment]
Hello. The same issue happens in `pytest_fixture_post_finalizer()` a few lines above.

Python 3.11.1, pytest-asyncio 0.20.3, using uvloop, and I have the strict mode for warnings (converting all warnings to errors in tests), so the test failures/errors look like the one below.

I wanted to suppress these warnings as this:

```
def pytest_configure(config):
    config.addinivalue_line('filterwarnings', 'ignore:There is no current event loop:DeprecationWarning:pytest_asyncio')
```

Unfortunately, the warning/exception still pops up when the routines are invoked via Click (the command-line framework) — somehow, this "ignore" more is not propagated down the stack.

---


```
============================= test session starts ==============================
platform linux -- Python 3.11.1, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/runner/work/kopf/kopf, configfile: pytest.ini
plugins: cov-4.0.0, aiohttp-1.0.4, asyncio-0.20.3, mock-3.10.0, timeout-2.1.0, aresponses-2.1.6
asyncio: mode=Mode.AUTO
………
==================================== ERRORS ====================================
_________________ ERROR at teardown of test_help_in_subcommand _________________

fixturedef = <FixtureDef argname='event_loop' scope='function' baseid=''>
request = <SubRequest 'event_loop' for <Function test_help_in_subcommand>>

    @pytest.hookimpl(trylast=True)
    def pytest_fixture_post_finalizer(fixturedef: FixtureDef, request: SubRequest) -> None:
        """Called after fixture teardown"""
        if fixturedef.argname == "event_loop":
            policy = asyncio.get_event_loop_policy()
            try:
>               loop = policy.get_event_loop()

/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/pytest_asyncio/plugin.py:381: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <uvloop.EventLoopPolicy object at 0x7f9ff7f7d550>

    def get_event_loop(self):
        """Get the event loop for the current context.
    
        Returns an instance of EventLoop or raises an exception.
        """
        if (self._local._loop is None and
                not self._local._set_called and
                threading.current_thread() is threading.main_thread()):
            stacklevel = 2
            try:
                f = sys._getframe(1)
            except AttributeError:
                pass
            else:
                while f:
                    module = f.f_globals.get('__name__')
                    if not (module == 'asyncio' or module.startswith('asyncio.')):
                        break
                    f = f.f_back
                    stacklevel += 1
            import warnings
>           warnings.warn('There is no current event loop',
                          DeprecationWarning, stacklevel=stacklevel)
E           DeprecationWarning: There is no current event loop

/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/asyncio/events.py:6[87](https://github.com/nolar/kopf/actions/runs/4106631395/jobs/7085111073#step:6:88): DeprecationWarning
```

**Comment by seifertm** [comment]
> You're welcome. I bet this affects a lot of users.
> 
> I'll reopen the issue, because we need to find a permanent solution that doesn't break in Python 3.12.

The deprecation of `asyncio.get_event_loop` was rolled back/slowed down. Only parts of the functionality have been deprecated in Python 3.12 and pytest-asyncio works fine with it. We'll probably have to move away from using `get_event_loop` eventually, but we're good for now.

**Comment by jpmckinney** [comment]
In case it helps anyone else who finds this issue, I had been running 3.10.2, and upgrading to the [latest 3.10 release](https://docs.python.org/3.10/whatsnew/changelog.html) got rid of the deprecation warnings.
