### ISSUE TITLE
DeprecationWarning: asyncio.async() function is deprecated, use ensure_future()

### ISSUE THREAD

**Issue by adamrothman** [pytest-dev/pytest-asyncio#50]
I am getting a ton of these warnings during test runs:

```
.tox/py36/lib/python3.6/site-packages/pytest_asyncio/plugin.py:77: DeprecationWarning: asyncio.async() function is deprecated, use ensure_future()
    asyncio.async(pyfuncitem.obj(**testargs), loop=event_loop))
```

Environment:
* Python 3.6.1
* pytest 3.1.0
* pytest-asyncio 0.5.0

**Comment by lelit** [comment]
This is because pytest 3.1 integrates the pytest-warnings.

**Comment by lelit** [comment]
As a quick workaround (specific for pytest-asyncio 0.5.0), I added the option `-Wignore:::pytest_asyncio.plugin:77` to the pytest command line.

**Comment by Tinche** [comment]
Acknowledged, thanks for the report.
