### ISSUE TITLE
0.6.0 version causing test failures with: There is no current event loop in thread 'MainThread'

### ISSUE THREAD

**Issue by hyzhak** [pytest-dev/pytest-asyncio#54]
Got Error:
```
RuntimeError: There is no current event loop in thread 'MainThread'.
```
For example:
https://travis-ci.org/botstory/botstory/builds/236994191#L594

Sources of unit test:
https://github.com/botstory/botstory/blob/develop/botstory/chat_test.py#L38
```python
@pytest.mark.asyncio
async def test_should_say(mock_interface):
    with answer.Talk() as talk:
        story = talk.story
        story.use(mock_interface)

        @story.on('hi there!')
        def one_story():
            @story.part()
            async def then(message):
                await story.say('Nice to see you!', message['user'])

        await talk.pure_text('hi there!')

        mock_interface.send_text_message.assert_called_once_with(
            recipient=talk.user,
            text='Nice to see you!',
            options=None,
        )
```

And the same error for many other async tests which are marked with `@pytest.mark.asyncio`, with fixtures and without it.

Deps are: https://github.com/botstory/botstory/blob/develop/requirements.txt
```
aiohttp==2.1.0
motor==1.1
pytest==3.1.0
pytest-aiohttp==0.1.3
pytest-asyncio==0.5.0
pytest-catchlog==1.2.2
pytest-cov==2.5.1
pytest-flakes==2.0.0
pytest-mock==1.6.0
yarl==0.10.2
```

previous version works fine, except [deprecation warning](https://travis-ci.org/botstory/botstory/builds/236994185#L489)

**Comment by Insoleet** [comment]
Same problem here.

**Comment by Tinche** [comment]
I'll take a look when I can, but getting me a minimal example would speed this up a lot.

**Comment by hyzhak** [comment]
@Tinche you can use my example (noted in this issue) if would like. It is open source.

**Comment by Tinche** [comment]
The problem is pytest-aiohttp.

Pytest-aiohttp treats every coroutine as a test function, so when you have this:

```
@pytest.mark.asyncio
async def test_blabla():
    pass
```
both ``pytest-asyncio`` and ``pytest-aiohttp`` will try to run it, and that's where the conflict will be.

I'm opposed to treating any coroutine (i.e. without a marker) as a ``pytest-asyncio`` test, because that precludes using other Python async frameworks like Curio or Trio, so I won't be changing this behavior and I consider the pytest-aiohttp approach wrong.

In the short term, just remove the ``pytest.mark.asyncio`` marker and let ``pytest-aiohttp`` run your test.

**Comment by hyzhak** [comment]
@Tinche thanks for feedback! And I will contact with @asvetlov to get additional information about this case

**Comment by achimnol** [comment]
As linked above, I have found similar regression *without* pytest-aiohttp.
After adding new test cases that does *not* use pytest-asyncio but creates & closes new event loops on their own, existing test cases that depends on pytest-asyncio began to break.
The interesting part is that not all pytest-asyncio test cases fails; only even-ordered ones fail. (You can check out the Travis CI log linked in the above issue)
