### ISSUE TITLE
async teardown_method warnning

### ISSUE THREAD

**Issue by Sube-py** [pytest-dev/pytest-asyncio#560]
```python
    @pytest.mark.asyncio
    async def teardown_method(self, client: AsyncClient):
        self.app.dependency_overrides = {}
        print("\n Teardown")
        await client.aclose()
```
`warning`:RuntimeWarning: coroutine 'APITestBase.teardown_method' was never awaited
framework: fastapi, and use httpx AsyncClient

**Comment by seifertm** [comment]
Your code snippet looks correct. However, it's impossible to pinpoint the issue when it cannot be reproduced.

Can you reduce your code until you have a minimal reproducible example that runs into this issue?
(i.e. an example that is as small as possible and reproducible meaning that one can copy and paste the code in one or more files and run pytest to see it fail)

**Comment by seifertm** [comment]
I'm closing the issue, because more information is needed, but the OP seems to be inactive.

Feel free to resume the discussion and/or reopen the issue.

**Comment by Sube-py** [comment]
> Your code snippet looks correct. However, it's impossible to pinpoint the issue when it cannot be reproduced.
> 
> Can you reduce your code until you have a minimal reproducible example that runs into this issue? (i.e. an example that is as small as possible and reproducible meaning that one can copy and paste the code in one or more files and run pytest to see it fail)

I'm so sorry that I forgot to reply you, I have avoided the warning by the following code.

```python
from syncer import sync

class APITestBase:
    app = app_server
    base_url = "http://127.0.0.1/api/v1"
    client = AsyncClient(app=app, base_url=base_url)

    @sync # use sync instead of pytest.mark.asyncio
    async def teardown_method(self, *args, **kwargs):
        self.app.dependency_overrides = {}
        await self.client.aclose()
        print("\n Teardown")
```
