### ISSUE TITLE
Support for Python versions pre-3.5 has been dropped

### ISSUE THREAD

**Issue by oberstet** [pytest-dev/pytest-asyncio#57]
This broke our CI (eg [here](https://travis-ci.org/crossbario/autobahn-python/jobs/239673195), and we are considering forking pytest-asyncio.

Could s.o. explain why support for Py < 3.5 was dropped? Any particular reason.

**Comment by Tinche** [comment]
The desire to start moving the codebase to async/await exclusively, mostly.

You can continue using 0.5 until you're ready to switch to 3.5+ or drop 3.3/3.4 compatibility (if you're a library). Feel free to fork if it makes sense for you, the license is what it is specifically to allow everyone to do that :)

My opinion is that migrating from 3.4 to 3.5 is very easy (as opposed to migrating from 2.7 to 3+) and if you're doing anything involving asyncio, very very worth it.

**Comment by oberstet** [comment]
@Tinche thanks for explaining! I agree for _app_ code: everyone should move to Python 3.5+.

But we can't do that, as we are maintaining libraries that must run on everything (including Python 2.7 + Trollius):

* https://github.com/crossbario/autobahn-python
* https://github.com/crossbario/txaio

We'll pin pytest-asyncio at 0.5 for now. I hate forking, and I don't have time now anyways;) I was just hoping that you might reconsider ..
