### ISSUE TITLE
How to use the same asyncio.Task between fixtures and each test coroutine so that they can have access to the same scoped db sessions

### ISSUE THREAD

**Issue by rnarkk** [pytest-dev/pytest-asyncio#624]
I've been trying to get the same `sqlalchemy.ext.asyncio.AsyncSession` instances by   `sqlalchemy.ext.asyncio.async_scoped_session` both from the initialisation methods of the Factory classes and from pytest fixtures provided as function arguments with each testcase. The problem is that the tasks in which the `async_scoped_session` is called are different, so the sessions provided as fixtures don't hold the pending states flushed by the Factory classes.

**Comment by graingert** [comment]
I think this is a dup of https://github.com/pytest-dev/pytest-asyncio/issues/127

@rnarkk have you tried using the anyio pytest plugin? It runs async fixture setup and teardown in the same task

**Comment by rnarkk** [comment]
@graingert Yes, I'm setting `pytestmark = pytest.mark.anyio` in each test file but seems I need more than that? Do I need to pass some anyio function as `scopefunc` argument to `async_scoped_session` to identify current scope?

**Comment by rnarkk** [comment]
Actually anyio doesn't seem to run async fixtures and testcases themselves in the same task.

**Comment by seifertm** [comment]
@rnarkk Is there a way you could provide a minimal, runnable reproducer for your problem? Otherwise, it will be hard to pinpoint your problem.

**Comment by seifertm** [comment]
@rnarkk Any update on this topic?

**Comment by rnarkk** [comment]
@seifertm What I've found is when I try to refer contextvars or async_scoped_session from different files, they It could never  be successful so I put both of them in conftest.py then It magically worked. Thank you for check-in.
