### ISSUE TITLE
Derive project version in docs from Git Tags

### ISSUE THREAD

**Issue by seifertm** [pytest-dev/pytest-asyncio#628]
The project version specified in `docs/source/conf.py` has not been bumped since v0.20.1.

The `release` field should be derived automatically from the version determined by setuptools_scm, so there's no need to adjust the version manually upon creating a release.

**Comment by marcolab** [comment]
Hi! I would like to work on this issue

**Comment by seifertm** [comment]
Great! Let me know if you encounter any issues or if you need a few pointers.

**Comment by marcolab** [comment]
I was thinking of simply doing the same as is done in `tools/get-version.py`. So using `importlib.metadata` to derive the version in `docs/source/conf.py`. Would that work?

**Comment by seifertm** [comment]
That sounds like a reasonable approach.

I noticed it's possible for the venv to contain an outdated version of pytest-asyncio. This may lead to outdated values for _release_, if we go with this approach. However, I think that this problem needs to be handled separately from this issue.

Your approach is the way to go in my opinion.

**Comment by menkotoglou** [comment]
Hey @marcolab, did you have the time to look into it? Maybe need a helping hand?

**Comment by ka28kumar** [comment]
Hello @seifertm,
We can get the version either using `importlib.metadata.version("pytest-asyncio")` or `setuptools_scm.get_version()`. Which one would you prefer?

**Comment by seifertm** [comment]
@ka28kumar I'd prefer the use of `importlib.metadata`, because it is part of the standard library in recent versions of Python.
