### ISSUE TITLE
Replace deprecated option to pypa/gh-action-pypi-publish action

### ISSUE THREAD

**Issue by seifertm** [pytest-dev/pytest-asyncio#699]
The *PyPI Upload* step in the *Deploy* job of the CI pipeline emits the following warning:
```
Warning: Input 'packages_dir' has been deprecated with message: The inputs have been normalized to use kebab-case. Use `packages-dir` instead.
```

The argument should be adjusted accordingly, in order to get rid of the deprecation warning.

**Comment by ujjwal123123** [comment]
Based on the information provided in the README and pypa/gh-action-pypi-publish#125, it seems that modifying packages_dir to packages-dir would suffice. Should I create a pull request for this change?

**Comment by seifertm** [comment]
@ujjwal123123 Yes, feel free to proceed. Thanks for double-checking!
