### ISSUE TITLE
[Feature request] add a loop fixture

### ISSUE THREAD

**Issue by asvetlov** [pytest-dev/pytest-asyncio#71]
People very often asked why `pytest-asyncio` and `pytest-aiohttp` are not compatible.
Well, AFAIK they are not mutually exclusive but the compatibility is not perfect still.

I had very strong objection for `pytest-asyncio` behavior: from my perspective `event_loop` fixture should call `asyncio.set_event_loop(None)` before running a test. It's prevent forgetting to pass `loop` param to calls like `asyncio.sleep()` etc.

But not I withdraw my objection: since Python 3.5.3 the coroutine always gets a running event loop regardless to `asyncio.set_event_loop()` param.

We still have many differences between `pytest-asyncio` and `pytest-aiohttp`: a need for special `@pytest.mark.asyncio` markup for `pytest-asyncio` and event loop naming.

In `pytest-asyncio` it is `event_loop` but int `pytest-aiohttp` the name is `loop`.

The `loop` name is used everywhere in `asyncio` documentation, I love to keep it (at least the name is shorter).

@Tinche would you consider adding the `loop` fixture as an alias for `event_loop`?

I'm not a `pytest` jedi, in my mind the fixture should look like:

```
@pytest.yield_fixture
def loop(event_loop):
    return event_loop
```

but maybe you have a better idea.

**Comment by Tinche** [comment]
Sure, I would be open to adding a `loop` alias to `event_loop`. I can put it in in a few days.

**Comment by asvetlov** [comment]
Not required anymore
