### ISSUE TITLE
attaching a watcher to an event loop breaks finalizer  

### ISSUE THREAD

**Issue by gaborbernat** [pytest-dev/pytest-asyncio#73]
In order to be able to handle ``asyncio.subprocesses`` with both ``stdout``, ``stderr`` callbacks one need to have a child watcher that's attached to the loop, so the ``event_loop`` needs to look something like:

```python
def get_event_loop():
    if sys.platform == 'win32':
        return asyncio.ProactorEventLoop()  # on windows IO needs this
    return asyncio.new_event_loop()  # default on UNIX is fine

@pytest.yield_fixture()
def event_loop():
    """pytest-asyncio customization"""
    loop = get_event_loop()
    if sys.platform != "win32":
        # on UNIX we also need to attach the loop to the child watcher for asyncio.subprocess
        policy = asyncio.get_event_loop_policy()
        watcher = asyncio.SafeChildWatcher()
        watcher.attach_loop(loop)
        policy.set_child_watcher(watcher)
    try:
        yield loop
    finally:
        loop.close()
```

Now the problem is that pytest-asyncio finalizer tries to attach back to the old event loop: https://github.com/pytest-dev/pytest-asyncio/blob/master/pytest_asyncio/plugin.py#L139, and at that point all watchers are also attached to that loop too. However, you cannot attach to a closed loop, so if the old loop is closed the finalizer fixture will throw an exception: ``raise RuntimeError('Event loop is closed')`` :disappointed: 

points of interest:
``attach_loop`` for watcher - https://github.com/python/cpython/blob/master/Lib/asyncio/unix_events.py#L758
``add_signal_handler`` check closed - https://github.com/python/cpython/blob/master/Lib/asyncio/unix_events.py#L84
``set_event_loop`` for policy - https://github.com/python/cpython/blob/master/Lib/asyncio/unix_events.py#L1007

As a work around setting the event loop at the start to ``None`` solves this, however maybe we should not attach back to closed loops, and instead just remove those loops.

**Comment by Tinche** [comment]
So which improvements specifically are you proposing?

* Improving the default event_loop fixture to return a ProactorEventLoop on Windows?
* Improving our child watcher support?
* Improving our finalizer to check if the old loop is already closed?

With sufficient rationale, I'd be open to merging in all of these :)

**Comment by gaborbernat** [comment]
I would probably propose all three. Here's what I did and made it work:

https://github.com/gaborbernat/tox3/blob/master/tests/conftest.py#L20

```python
@pytest.yield_fixture()
def event_loop():
    """pytest-asyncio customization"""
    if sys.platform != "win32":
        asyncio.set_event_loop(None)  # see https://github.com/pytest-dev/pytest-asyncio/issues/73
    loop = get_event_loop()
    if sys.platform != "win32":
        # on UNIX we also need to attach the loop to the child watcher for asyncio.subprocess
        policy = asyncio.get_event_loop_policy()
        watcher = asyncio.SafeChildWatcher()
        watcher.attach_loop(loop)
        policy.set_child_watcher(watcher)
    try:
        yield loop
    finally:
        loop.close()
```

Setting the event loop to None can be removed if we check that we only re-attach if the loop is not closed yet in the finalizer. Or so I think.

**Comment by Tinche** [comment]
Could you submit a PR or two?

**Comment by gaborbernat** [comment]
@Tinche sure :+1:

**Comment by abolger** [comment]
Note since this is still not fixed for future visitors: without the overridden event loop as shown by @gaborbernat, symptoms of this issue include getting "RuntimeError: Event loop is closed" error even when you have _just checked_ that your event_loop is open, and also can show up as bad isolation- i.e. running a parameterized test will pass the first time and not the second because an attached watcher is persisting on the loop from the previous test. Basically, if your code under test ever uses asyncio.get_child_watcher().attach_loop under the hood, you _really need_ the fixture adjustment above to avoid mystery errors as you add tests.
