### ISSUE TITLE
TypeError: __call__() got an unexpected keyword argument 'specname' in version 0.23 pytest-asyncio

### ISSUE THREAD

**Issue by jefflieu** [pytest-dev/pytest-asyncio#756]
Recent update to pytest-asyncio 0.23 is showingthis error:
```
  File "/usr/local/lib/python3.9/site-packages/pytest_asyncio/plugin.py", line 501, in <module>
    @pytest.hookimpl(specname="pytest_pycollect_makeitem", tryfirst=True)
TypeError: __call__() got an unexpected keyword argument 'specname'
```
My pytest and pytest-asyncio version:
```
Name: pytest
Version: 7.4.4
Summary: pytest: simple powerful testing with Python
Home-page: https://docs.pytest.org/en/latest/
Author: Holger Krekel, Bruno Oliveira, Ronny Pfannschmidt, Floris Bruynooghe, Brianna Laugher, Florian Bruhin and others
Author-email: 
License: MIT
Location: /usr/local/lib/python3.9/site-packages
Requires: iniconfig, pluggy, tomli, exceptiongroup, packaging
Required-by: pytest-asyncio


Name: pytest-asyncio
Version: 0.23.0
Summary: Pytest support for asyncio
Home-page: https://github.com/pytest-dev/pytest-asyncio
Author: Tin Tvrtković <tinchester@gmail.com>
Author-email: tinchester@gmail.com
License: Apache 2.0
Location: /usr/local/lib/python3.9/site-packages
Requires: pytest
Required-by: 
```

Let me know if this has been reported. Thanks.

I believe that you don't need any test code to trigger that error. Just install those versions and run 
```
pytest --version
```

**Comment by yxy** [comment]
any solutions ?

**Comment by jefflieu** [comment]
Unfortunately no, I'm downgrading pytest-asyncio to 0.21 to move forward.
I don't know the story between pytest-asyncio and pytest, how are they maintained and tested new versions against each other. 
I'm kind of waiting to see opinions from the experts.
I'm using them but not understand the underlying code very well.

**Comment by seifertm** [comment]
Thanks for the report. Each commit to pytest-asyncio is type-checked with mypy. Unfortunately, pytest-asyncio is currently using an outdated version of mypy, so some typing issues may not be reported properly.

This has been recorded as an issue in #596, so I'll close this one as a duplicate.
