### ISSUE TITLE
Hypothesis integration raises internal error when collecting `RuleBasedStateMachine`

### ISSUE THREAD

**Issue by Zac-HD** [pytest-dev/pytest-asyncio#758]
*Initially reported in https://github.com/HypothesisWorks/hypothesis/issues/3850*

> The bug can be reproduced by installing pytest_asyncio and hypothesis, then trying to run the following test:
> 
> ```
> from hypothesis.stateful import RuleBasedStateMachine
> class StatefulTest(RuleBasedStateMachine):
>     def __init__(self):
>         super().__init__()
>  
> TestStorage = StatefulTest.TestCase
> ```
> 
> ```python-traceback
> INTERNALERROR> Traceback (most recent call last):
> INTERNALERROR>   ...
> INTERNALERROR>   File ".../python3.11/site-packages/pytest_asyncio/plugin.py", line 371, in pytest_collection_modifyitems
> INTERNALERROR>     and _hypothesis_test_wraps_coroutine(function)
> INTERNALERROR>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> INTERNALERROR>   File ".../python3.11/site-packages/pytest_asyncio/plugin.py", line 377, in _hypothesis_test_wraps_coroutine
> INTERNALERROR>     return _is_coroutine(function.hypothesis.inner_test)
> INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^
> INTERNALERROR> AttributeError: 'function' object has no attribute 'hypothesis'
> ```

To fix this, we should avoid assuming that the `.hypothesis` attribute exists in 
https://github.com/pytest-dev/pytest-asyncio/blob/463ce984677f0ac965f225c3b7ac14ebf43adad6/pytest_asyncio/plugin.py#L482-L487

As a fix, I'd suggest:

```python
        return (
            getattr(func, "is_hypothesis_test", False)
            and getattr(func, "hypothesis", None)
            and asyncio.iscoroutinefunction(func.hypothesis.inner_test)
        )
```

Note that there's no simple to support async stateful testing; [the `hypothesis-trio` project](https://github.com/python-trio/hypothesis-trio) is essentially a fork of our upstream stateful testing module with async handling injected in many places.  My suggestion therefore continues to treat asyncio stateful tests as out of scope, since I don't think there's sufficient demand to be worth the maintainence burden.

**Comment by eivindjahren** [comment]
It seems that this is no longer an issue in pytest-asyncio==0.23.3. I suggest closing the issue.

**Comment by seifertm** [comment]
Thanks for the cross-reference to the Hypothesis issue and for the improvement suggestion. I amended the check for Hypothesis tests as suggested.

Pytest-asyncio v0.23 had lots issues with test collection, unfortunately. These caused an `INTERNALERROR` in pytest at collection time.
