### ISSUE TITLE
Should event_loop fixture call asyncio.set_event_loop()?

### ISSUE THREAD

**Issue by adamrothman** [pytest-dev/pytest-asyncio#80]
I use pytest and pytest-asyncio to test a few Tornado applications. I had some trouble (see https://github.com/tornadoweb/tornado/issues/2324) with Tornado getting a different event loop from the one created by pytest-asyncio's `event_loop` fixture.

This can be fixed by overriding Tornado's default testing behavior to use the "current" loop, rather than creating a new one. The issue is that pytest-asyncio does not call `asyncio.set_event_loop` with the loop it creates in the `event_loop` fixture – without which, there is no "current" loop.

I'd like to propose change the `event_loop` fixture to look like this:

```python
@fixture
def event_loop(request):
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    yield loop
    loop.close()
    asyncio.set_event_loop(None)
```

How does that sound? I'm happy to submit a PR, but I wanted to get feedback on the idea first.

**Comment by Tinche** [comment]
Hm, I think it used to be considered bad form to call asyncio.get_event_loop before, but now it's considered OK, so we might enable this. @asvetlov thoughts?

In any case, we use a fixture hook to do things like this in order to keep the event_loop fixture very simple, so it's simple to override.

**Comment by asvetlov** [comment]
It is safe starting from Python 3.5.3

**Comment by asvetlov** [comment]
pytest-asyncio operates with async tests only.
The async test always have an event loop available by both `asyncio.get_event_loop()` and `asyncio.get_running_loop()` calls.
There is no need to explicitly call `asyncio.set_event_loop()`, it is done by `loop.run_untile_complete()` already.
