### ISSUE TITLE
You need to install a suitable plugin for your async framework, for example:

### ISSUE THREAD

**Issue by tyler-suard-parker** [pytest-dev/pytest-asyncio#843]
I keep getting this error message even after installing pytest-asyncio and restarting my terminal.  Python 3.9.0, Pytest 8.2.1

**Comment by seifertm** [comment]
Without any code or further description of your problem, I cannot help.

One possible reason is that pytest-asyncio has two different [test discovery modes](https://pytest-asyncio.readthedocs.io/en/latest/concepts.html#test-discovery-modes), _strict_ and _auto_. In strict mode (the default), pytest-asyncio doesn't process tests unless you apply the `@pytest.mark.asyncio` decorator to them.
