### ISSUE TITLE
Unify documentation build process for local and CI environment

### ISSUE THREAD

**Issue by seifertm** [pytest-dev/pytest-asyncio#917]
Currently, the documentation can be built locally using `tox run -e docs` or as part of the CI via readthedocs. However, the build processes are different. This makes it hard to reproduce readthedocs builds locally.

The goal of this issue is to have the same build process for docs, both locally and in the CI.

see https://github.com/pytest-dev/pytest-asyncio/pull/912

**Comment by ka28kumar** [comment]
Hello @seifertm ,
I'm the author of #912, can I take this up?
Would be a good introduction to using ReadTheDocs and CI pipelines.

**Comment by ka28kumar** [comment]
Hello @seifertm 
I'm looking at other issues as well. No worries, I'll be here helping out with this project.
