### ISSUE TITLE
FixtureFunction TypeVar pollutes mypy annotations for arbitrary types

### ISSUE THREAD

**Issue by pechersky** [pytest-dev/pytest-asyncio#919]
I have `pytest-asyncio` and `requests` installed in my python environment, with `mypy==1.11.1`. I use VSCode as my IDE. Once I installed `pytest-asyncio`, the inferred type annotations for many things got much more complex, and now say:
`FixtureFunction[SimpleFixtureFunction@FixtureFunction, FactoryFixtureFunction@FixtureFunction]`
I also think these catch-all typevars end up slowing down the mypy typechecking, but that's only a guess.

Here is an example (sorry for the screenshot, not sure how to get command line output to display this):
![image](https://github.com/user-attachments/assets/5e322120-4089-4711-af9b-694c77bd7697)

Is there a way to scope these typevars to not be used for other files? Or to restructure `pytest-asyncio`'s use of them?

**Comment by somiandras** [comment]
@pechersky It was diagnosed as a bug in pyright, see this discussion: https://github.com/microsoft/pyright/discussions/8608

**Comment by seifertm** [comment]
My understanding is that this doesn't need any action from pytest-asyncio for the time being.

**Comment by ifedapoolarewaju** [comment]
sharing this as a workaround for anyone who is having this challenge with Cursor and isn't able to update Pylance (Cursor has an older pinned version of Pylance). What I have settled for is to exclude my test files from Pylance analysis (see screenshot for relevant setting).

<img width="879" alt="Image" src="https://github.com/user-attachments/assets/adda68d6-1e56-4ec2-b23b-887a88872882" />
