### ISSUE TITLE
Package License and tests in sdist tarball to pypi.io

### ISSUE THREAD

**Issue by mimi1vx** [pytest-dev/pytest-asyncio#94]
Please include tests and License in tarball.

Hint: use MANIFEST.in file:D

**Comment by Tinche** [comment]
How about a quick PR? :)

**Comment by seifertm** [comment]
Both the LICENSE file and tests are packaged in pytest-asyncio-0.17.0. I haven't checked older releases, but I'm closing this issue as solved.
